### ISSUE TITLE
Extra field with count of cards that have same unknown morphs

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#103]
so that I can be sure there will be other notes when I delete one.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 you can do this manually in the sidebar of the browser select the field after clicking it in the search bar a query will appear. After the query type the morph

**Comment by HQYang1979** [comment]
> @HQYang1979 you can do this manually in the sidebar of the browser select the field after clicking it in the search bar a query will appear. After the query type the morph 

Yes, but it is not convenient. I can also press L to see all the notes. It's just that I can glance at it and know there are other notes to come. Because the first note shown might be having imperfect audio, the sentence not contextual etc.

**Comment by mortii** [comment]
@HQYang1979 Where would you like that number to be displayed?

**Comment by HQYang1979** [comment]
> @HQYang1979 Where would you like that number to be displayed?

I think it would have to be a new field.

**Comment by mortii** [comment]
> I think it would have to be a new field.

Interesting.... I think I like that idea. I'm going to consider it some more and I'll get back to you.

**Comment by mortii** [comment]
I'll add this after spacy is implemented
