### ISSUE TITLE
Enable extra fields only for some note types

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#104]
**Is your feature request related to a problem? Please describe.**
Some people use "Incremental reading", which means cards containing lots of text.
anki-morphs as discussed in #102 adds extra fields either to no note type, or to all note types.
That means, if I want to add am-unknowns to my small cards, it will also be added to my big cards, making them even bigger.

**Describe the solution you'd like**
Checkboxes in the table where dropdowns were.

**Comment by Vilhelm-Ian** [comment]
I actually prefer the current implementation it's so much simpler than anything previous

**Comment by mortii** [comment]
@aleksejrs I agree that a more granular approach would be better, but I can't think of a way of displaying it nicely. The table view approach I tried in #99 is hideous beyond belief:

![image](https://github.com/mortii/anki-morphs/assets/15674619/f87cfa9b-6be8-4009-8780-64dd2fb935a3)
 
A tree view would probably be better, but that could get really ugly as well, so I'm not sure.

If you have a specific suggestion or example of how to display it in a good way, then please present it and I'll gladly implement it.

**Comment by mortii** [comment]
released in [v.0.12](https://github.com/mortii/anki-morphs/releases/tag/v0.12.0-alpha), thanks for the suggestion!
