### ISSUE TITLE
Morphman 23

### ISSUE THREAD

**Issue by wrinkledeth** [mortii/anki-morphs#107]
Hello, will this support the new Anki version 23?

**Comment by HQYang1979** [comment]
No problem so far.
![image](https://github.com/mortii/anki-morphs/assets/74698160/e1e73bd0-d56f-49b1-974c-d62de457ea82)

**Comment by mortii** [comment]
> Hello, will this support the new Anki version 23?

Yep, I'm using Anki 23.12 with no problem :+1:

**Comment by wrinkledeth** [comment]
thanks very much sir!
