### ISSUE TITLE
Frequency.csv format

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#108]
Do I have to follow exact the same format?

![image](https://github.com/mortii/anki-morphs/assets/74698160/99365dad-4ae0-4ea2-9f39-934665607e9b)

Can it be like this?

![image](https://github.com/mortii/anki-morphs/assets/74698160/c58fce7c-11fa-4294-84f8-f02c1ff519d2)

It's quite difficult to have exact same format for all other languages.

I know we can generate our own frequency.csv, but again it is difficult to have a corpus that can be used for generation.

No other languages like Japanese....

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 it's entirely possible to use spacy to convert an already existing frequency list to a frequency list in the format that anki-morphs requires. Please be patient for the spacy update

**Comment by mortii** [comment]
> I know we can generate our own frequency.csv, but again it is difficult to have a corpus that can be used for generation.

@HQYang1979 Do you mean that it is hard to find a corpus that has .txt files?

**Comment by HQYang1979** [comment]
> @HQYang1979 it's entirely possible to use spacy to convert an already existing frequency list to a frequency list in the format that anki-morphs requires. Please be patient for the spacy update

good to know

**Comment by HQYang1979** [comment]
> > I know we can generate our own frequency.csv, but again it is difficult to have a corpus that can be used for generation.
> 
> @HQYang1979 Do you mean that it is hard to find a corpus that has .txt files?
> 

yes, I cannot find spanish and English subtitle corpus like the one you recomend for Japanese

**Comment by mortii** [comment]
> yes, I cannot find spanish and English subtitle corpus like the one you recomend for Japanese

Yeah, it's not always very easy. At some point I should probably find good sources and add more frequency files to the guide that can be downloaded.

Hugging face and other machine learning communities have large collections of text that can be used, e.g: https://huggingface.co/datasets/mc4 has terabytes of text, but it's not very convenient to download and use.

**Comment by HQYang1979** [comment]
I guess I have to make my own frequency list based on the Routledge series.

May I ask how do the morphemizer deal with situations like these:
![image](https://github.com/mortii/anki-morphs/assets/74698160/36e83ff2-155e-47c0-bc53-aa1baea4620d)
知る、しる、知ている。。。
Or in English:
Write, Wrote, Written, Writing

Can I do something like this:

![image](https://github.com/mortii/anki-morphs/assets/74698160/8d450f67-f9fd-45f1-b251-c384a545cf36)

**Comment by HQYang1979** [comment]
I deliberately added some words to the top of the frequency list, but these words do not show up first in the review. I have no idea why, I should be getting the format correct.
[jp_frequency.csv](https://github.com/mortii/anki-morphs/files/13793600/jp_frequency.csv)
And when I use this frequency list for English, I got an error message.
![image](https://github.com/mortii/anki-morphs/assets/74698160/84497fc4-76c4-4267-986d-b5a20f6f36fd)
[en_frequency.csv](https://github.com/mortii/anki-morphs/files/13793610/en_frequency.csv)

**Comment by HQYang1979** [comment]
> @HQYang1979 the format for the english frequency list should be correct. Can you share the error you got

![image](https://github.com/mortii/anki-morphs/assets/74698160/24585ab7-1e3a-47ff-af57-8d3472bbb442)

This is the steps:
![image](https://github.com/mortii/anki-morphs/assets/74698160/8cb81441-6ed2-470d-8ffd-a053976564ea)

The error happens on during Saving ankimorphs.db....
![image](https://github.com/mortii/anki-morphs/assets/74698160/05352424-5a57-4d61-a1e0-08fe2d05b624)

**Comment by mortii** [comment]
@HQYang1979 are you using spaCy? if not then the english frequency file will cause en error since the content in the two columns should be the same. It's dumb and unintuitive, I know.

**Comment by HQYang1979** [comment]
> @HQYang1979 are you using spaCy? if not then the english frequency file will cause en error since the content in the two columns should be the same. It's dumb and unintuitive, I know.

No, I do not use spaCy... OK, I get it, it is because of no morphemizer, right?

**Comment by mortii** [comment]
@HQYang1979 weird, I'll take a  look later.

**Comment by HQYang1979** [comment]
@mortii 

> @HQYang1979 are you using spaCy? if not then the english frequency file will cause en error since the content in the two columns should be the same. Only when spacy is used should the two columns be different.

I am still getting the same error message now using spaCy with two different columns.

**Comment by mortii** [comment]
1. I went to this website: https://www.corpusdata.org/formats.asp and downloaded the "Linear text COCA: 8.9 mw" sample corpus
2. Using the frequency file generator with the 'spaCy: en_core_web_sm' morphemizer I generated this file: 
[en-frequency-coca.csv](https://github.com/mortii/anki-morphs/files/13801197/en-frequency-coca.csv)
3. Selecting that file in the settings for the english deck successfully sorted the cards in the order of that frequency file.

> I am still getting the same error message now using spaCy with two different columns.

Are you manually creating these frequency files? If so then then the morphs might be different from what the morphemizer produces and recognizes, and then everything might break.

**Comment by HQYang1979** [comment]
> Are you manually creating these frequency files? If so then then the morphs might be different from what the morphemizer produces and recognizes, and then everything might break.

Yes, I manually created these frequency files. The reason is of prioritizing learning, I think it is a more targeting learning method than just generating from a corpus.

**Comment by mortii** [comment]
> Yes, I manually created these frequency files. The reason is of prioritizing learning, I think it is a more targeting learning method than just generating from a corpus.

Completely understandable, and it is theoretically possible to do as long as the morphs match what the morphemizer finds and recognizes. 

> I deliberately added some words to the top of the frequency list, but these words do not show up first in the review. I have no idea why, I should be getting the format correct.
> ![image](https://github.com/mortii/anki-morphs/assets/15674619/c7f4a470-fff9-430c-82ba-08303415e2aa)

Reordering should also work fine. Maybe the cards don't show up first because there are other morphs on the cards that give the cards a higher difficulty? If you create cards with just those morphs then they should show up first.

> Can I do something like this:
> ![image](https://github.com/mortii/anki-morphs/assets/15674619/63fda467-0a85-4bda-b524-c6740ec92b14)

No, two columns only. You would have to do something like this:
```
write, wrote
write, written
....
```

**Comment by mortii** [comment]
> Yes, I manually created these frequency files. The reason is of prioritizing learning, I think it is a more targeting learning method than just generating from a corpus.

@HQYang1979 I thought of a way you could do this relatively easily.
1. I created a `write-conjugations.txt` file in a folder called `english`, that looks like this:
```
write
wrote
written
writing
```
2. I used the frequency file generator with the morphemizer: `spaCy: en_core_web_sm` on the `english` folder and got this frequency file:
```
Morph-base,Morph-inflected
write,writing
write,write
write,wrote
write,written
```

Now you know the format that the morphemizer recognizes these words, and you can put them into other frequency files if you want.

You could theoretically do this with all frequency word lists, but I that might give you some false-positives since the words are not in context, so I'm not sure I recommend it.

**Comment by HQYang1979** [comment]
thank you for your thought, I'll look into  it.

**Comment by mortii** [comment]
@HQYang1979 do frequency files work for you now?

**Comment by HQYang1979** [comment]
> @HQYang1979 do frequency files work for you now?

I find it not convenient and stop using the frequency files.

**Comment by mortii** [comment]
@HQYang1979 Ok, thank you for the feedback :+1:
