### ISSUE TITLE
Add option to add already known words

### ISSUE THREAD

**Issue by xyaman** [mortii/anki-morphs#109]
I like to keep a minimal number of decks in Anki, and I wish to have the flexibility of adding known words to the database without the necessity of associating them with a specific deck. Something similar to what Morphman does with its database manager.

Morphman database manager allows the creation of a database file from a text file. If it's named "external.db", Morphman will considers all those words as known. This way, I can remove cards that are already 0T o delete decks without loosing known cards and avoiding useless reviews.

Maybe adding a database manager is too much, but maybe a simple script or a guide to add known words from a text file to the main database (or to an external one) would be nice.

**Comment by Vilhelm-Ian** [comment]
Basically we can do what we already do with names.txt . Just not ignore the words

**Comment by mortii** [comment]
@xyaman Thanks for the suggestion! It's a good idea, I like it. 

> Basically we can do what we already do with names.txt . Just not ignore the words

True, it might be a little more complicated if we care about inflections though, then we would have to use a csv files in the same format as the frequency files.

**Comment by mortii** [comment]
I'm thinking we could have a "Export Known Morphs" feature, which creates a csv files in the same format as the frequency file, and then we can have another option to read said file when recalcing.

**Comment by xyaman** [comment]
Thanks for considering it! I think a csv is a very good idea.

**Comment by mortii** [comment]
Okay, my current thinking is that we should have a 'known_morphs' folder, which is basically identical to the 'frequency_files' folder--they both contain csv files with the morphs stored as tuples (lemma, inflection). The nice thing about this is that you could create frequency files from media you already know and just place them in the 'known_morphs' folder.

In the recalc tab in settings we have an option to read those files:
![Screenshot from 2024-01-10 10-52-47](https://github.com/mortii/anki-morphs/assets/15674619/8bd1e100-f334-409c-866f-e67731865b05)

The morph exporter dialog should have at least these two options:
![Screenshot from 2024-01-10 10-50-15](https://github.com/mortii/anki-morphs/assets/15674619/773de1c9-bcab-4721-8015-967031d4752c)

Any suggestions/feedback is welcome!

**Comment by xyaman** [comment]
I think its very good. It's looks flexible, easy to manipulate (just csv) and the settings are simple.

**Comment by mortii** [comment]
I have a working version, I now just need to update the guide then I'll release it.

**Comment by mortii** [comment]
Released in [v0.15](https://github.com/mortii/anki-morphs/releases/tag/v0.15.0-alpha)!

Let me know if you experience any bugs, or if you have any other suggestions :)

**Comment by xyaman** [comment]
It worked and no problems until now. Thanks!
I'll let you know if I find bugs.
