### ISSUE TITLE
Add option to make U and A in the toolbar display 'true' knowns

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#122]
Right now they actually show 'seen' morphs, i.e., morphs you have reviewed at least once. This can be misleading, but it can also be more motivating because the numbers go up faster that way.

the current approach of showing 'seen' numbers should still be the default perhaps, but there should definitely be an option to use true 'known' numbers instead.

**Comment by Vilhelm-Ian** [comment]
I think a good heuristic is. True knowns to show morphs that are in mature cards

**Comment by mortii** [comment]
Yeah, this is simply done by using the 'min. interval for known morphs' config variable.
