### ISSUE TITLE
Add in the styling example for the am-highlighted section an example to change colors for the dark theme 

### ISSUE THREAD

**Issue by cocowash** [mortii/anki-morphs#123]
## What is the current documentation?
At the moment, the styling presented in the am-highlighted section is shared between light and dark theme of Anki 

[//]: # (Please add a link to the current docs page)
https://mortii.github.io/anki-morphs/user_guide/setup/settings/extra-fields.html

## What changes do you suggest?
Recommend the use of a class to make specific changes only for the dark theme.  
For example, I use: 
```
[morph-status=unknown] { background-color: #f7867e; } /* red */
[morph-status=learning] { background-color: #ffff99; } /* yellow */
[morph-status=known] { background-color: #49f53e; } /* green */
body.nightMode [morph-status=unknown] { background-color: #b74d4d; } /* red */
body.nightMode [morph-status=learning] { background-color: #ccad50; } /* yellow */
body.nightMode [morph-status=known] { background-color: #27961f; } /* green */
```

In this way this is tweaked so the color is best for each theme.

**Comment by mortii** [comment]
@cocowash Great idea, thank you!

**Comment by cocowash** [comment]
> @cocowash Great idea, thank you!
On the contrary, thank you for such a great add-on

**Comment by mortii** [comment]
Done: https://mortii.github.io/anki-morphs/user_guide/setup/settings/extra-fields.html#using-am-highlighted

Thanks!
