### ISSUE TITLE
morphs not splitting correctly

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#125]
> "Ahnung.Ich" should not be considered a morpheme 

_Originally posted by @cocowash in https://github.com/mortii/anki-morphs/issues/124#issuecomment-1890433389_

**Comment by mortii** [comment]
spaCy does not split text on periods:

``` python
expression = "Keine Ahnung.Ich".lower()
doc = nlp(expression)

for w in doc:
    print(f"w.text: {w.text}")

# output:
# w.text: keine
# w.text: ahnung.ich
```

this is for text like "10 a.m." to get  not get split into -> [10, a, m]

if there is a new line or whitespace then it works:
``` python
expression = "Keine Ahnung.\nIch".lower()

# output:
# w.text: keine
# w.text: ahnung
# w.text: .
# w.text: ich

```

So this basically means that malformed text will produce the wrong morphs, and there is not a whole lot we can do about it unfortuntely...

**Comment by Vilhelm-Ian** [comment]
We can just add to the guide instructions for people to use a regex like this
![image](https://github.com/mortii/anki-morphs/assets/81630959/3120036d-c0d1-4766-a3df-9adf1ecb37e2)
thre is a space after the dot

**Comment by mortii** [comment]
@Vilhelm-Ian Interesting! I've never used the find and replace feature in anki, it definitely seems like it could be useful here.

**Comment by Vilhelm-Ian** [comment]
Once I told HQ how to remove all the html from his cards that was added by the highlight feature with regex. Couldn't find the therad

**Comment by mortii** [comment]
> Once I told HQ how to remove all the html from his cards that was added by the highlight feature with regex. Couldn't find the therad

Ah yes, I remember.

issue #124 and this have now converged, so I'll close this one.
