### ISSUE TITLE
Ability to skip unknown morphs until a later date

### ISSUE THREAD

**Issue by alexnigelsmith** [mortii/anki-morphs#129]
Example:
You go to learn your cards for the day, and AnkiMorphs gives you a word to learn. However, the cards you have aren't the best quality sentences, or you still don't understand the sentence after looking up the new word.

Suggestion:
Add the ability to skip a morph until a later date. This could possibly get added to a dropdown in the settings page so you can easily see which morphs you have skipped, allowing you to release them at a later date. Although this can probably be done manually by editing the frequency document that is generated, you would have to do this every time you create a new frequency list.

**Comment by mortii** [comment]
@alexnigelsmith Interesting idea! I'll mull it over for a bit and get back to you!

**Comment by mortii** [comment]
@alexnigelsmith could you not just bury those cards?

**Comment by alexnigelsmith** [comment]
> @alexnigelsmith could you not just bury those cards?
> 
> EDIT:
> 
> > @alexnigelsmith could you not just bury those cards?
> 
> Never mind that, the obvious counter is that it could effect many cards, so manually burying them could be impractical.
> 
> Let me try get a better understanding of what you would like to see happen: Say you want to skip the morph "world". What should happen to the cards that have the morph "world" on them? Should those cards be modified during recalc, or on the fly when reviewing them?

Let's say the next word to learn is 'world'. There are 4 possible cards to choose from in your anki deck. However, even after looking at the definition, you still don't understand any of the sentences for it to be beneficial enough to rep in anki. Instead of just blindly repping the card hoping you will understand it eventually, I instead propose an option to 'temporarily' flag this word in the frequency list to skip it. This could potentially happen with 4 consecutive words in a frequency list, so I think it would be beneficial to have an option 'skip past' these words in the frequency list. 

Perhaps there could be an option when reviewing to flag this morph as 'learn later' (or something similar). This will then modify the freqency list, which would then require a recalc for the change to take effect. These words could be stored somewhere in the settings, and you could 'release' this morphs which would allow i+1 cards with the unknown morph to be shown again.

**Comment by mortii** [comment]
@alexnigelsmith I don't like tying this feature to frequency lists because not everyone uses them.

It just occurred to me that this feature could be made very similar to [names.txt](https://mortii.github.io/anki-morphs/user_guide/setup/names.html), where you add morphs to a txt file, and if those morphs are found on a card then it is buried/moved to the back of the queue or something. What do you think about that?
