### ISSUE TITLE
sqlite3.OperationalError: no such column: morph_lemma

### ISSUE THREAD

**Issue by wrinkledeth** [mortii/anki-morphs#131]
I updated anki morphs and it looks like something broke: 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 537, in after_answer
  File "aqt.reviewer", line 547, in _after_answering
  File "_aqt.hooks", line 4173, in __call__
  File "/Users/zen/Library/Application Support/Anki2/addons21/472573498/__init__.py", line 269, in insert_seen_morphs
    am_db.update_seen_morphs_today_single_card(card.id)
  File "/Users/zen/Library/Application Support/Anki2/addons21/472573498/ankimorphs_db.py", line 183, in update_seen_morphs_today_single_card
    self.con.execute(
sqlite3.OperationalError: no such column: morph_lemma

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-01-01T21:16, 'None', '']
CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2023-10-30T14:57, 'None', '']
LPCG LyricsPoetry Cloze Generator ['2084557901', 2023-12-06T22:43, 'None', '']
ReColor ['688199788', 2023-04-24T08:23, '2.5', mod]
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
ankimorphs-alpha ['472573498', 2024-01-11T07:04, 'None', mod]

===IDs of active AnkiWeb add-ons===
1771074083 1788670778 2055492159 2084557901 472573498 688199788

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by wrinkledeth** [comment]
I fixed it, it looks like after I updated anki-morphs, the db got removed? The morph counters were showing (U:? A:?)

After i did a re-calc, everything worked properly. 

Perhaps you could add this into the docs somewhere?

**Comment by mortii** [comment]
> Perhaps you could add this into the docs somewhere?

@wrinkledeth It's was described in the [v0.14 changelog](https://github.com/mortii/anki-morphs/releases/tag/v0.14.0-alpha), which is linked in both the docs and the add-on itself. It can get lost quickly though, but that is also kind of a good thing since the problem was transient. I'm not sure how to do it in a better way :man_shrugging: 

Glad you got it working again!
