### ISSUE TITLE
Can't close the "Insertig into anki collection" screen

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#14]
I tried clicking the x button and pressing alt-f4 but it wouldn't stop

**Comment by mortii** [comment]
Yeah, that seems to be a QueryOp problem... I'll look into it. Thank  you!

**Comment by mortii** [comment]
Found a potential solution: https://forums.ankiweb.net/t/how-to-cancel-a-background-task/19763/5

**Comment by mortii** [comment]
The user can now stop recalc by clicking 'x' when caching or updating is happening. It won't work during the "Insertig into anki collection" screen because the inserting does not happen in a loop so there is nowhere for the interrupt to happen unfortunately.
