### ISSUE TITLE
Readability Report Generator does not skip a directory with a supported extension

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#142]
**Describe the bug**
A directory with .txt trips RRG up.

**To Reproduce**
1. Create a directory name "directory.txt" in a Readability Analyzer corpus directory.
2. Run Readability Report Generator on the corpus.

```
Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "…/.local/share/Anki2/addons21/472573498/generator_dialog.py", line 232, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "…/.local/share/Anki2/addons21/472573498/readability_report_generator.py", line 147, in _background_generate_report
    with open(input_file, encoding="utf-8") as file:
IsADirectoryError: [Errno 21] Is a directory: '…/fsrs/fsrs4anki.wiki.txt'
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Anki Version 23.12
 - AnkiMorphs Version 20.17MB. Updated 2024-01-27.

**Comment by mortii** [comment]
> IsADirectoryError: [Errno 21] Is a directory: '…/fsrs/fsrs4anki.wiki.txt'

I haven't considered files that have double extensions like this. I'll look into it.

**Comment by mortii** [comment]
@aleksejrs I'm not able to reproduce the problem.

With this file structure:
```
ja-test-report/
    - fsrs/
       -  fsrs4anki.wiki.txt
    - test_ja_1.txt
    - test_ja_2.txt
```

When I select the `ja-test-report` directory then I successfully get a report on all three files.

**Comment by mortii** [comment]
> Create a directory name "directory.txt" in a Readability Analyzer corpus directory.

Oh wait, did you give a directory an extension? If that's the case then it's unsupported behavior.

**Comment by aleksejrs** [comment]
Can't it just check?
The directory was a copy of the wiki where I added ".txt" to ".md" files for MorphMan.

**Comment by mortii** [comment]
> Can't it just check?

I mean, in theory it's probably possible. That being said, I have never seen, nor heard of a directory having an extension before, so adding a new check for that would unnecessarily slow down an already slow process imo. Better to just remove the extension.

Btw, that is an amazing QA test, I'll definitely remember it.

**Comment by aleksejrs** [comment]
It could be something like

```
try:
    with open(input_file, encoding="utf-8") as file:
except IsADirectoryError:
    pass
```

So it would not check until the error happens.

**Comment by aleksejrs** [comment]
@mortii If it just skips processing the directory as a file and still processes the files within it, I see no fundamental problem with the file structure.
A Windows user would think a question mark is a problem with the file structure (as Anki does when exporting cards).
What if my directory was from a Moldovan website and ended with `.md`?

**Comment by mortii** [comment]
> The directory was a copy of the wiki where I added ".txt" to ".md" files for MorphMan.

@aleksejrs Could you give me the steps you used to copy a wiki that ended up with having a directory with an extension?

**Comment by aleksejrs** [comment]
@mortii I made a copy of the wiki, renamed the files in it, and renamed the directory to indicate that it contains txt files.

.md or any other TLD in a file name, however, would come from a downloader like httrack or DownThemAll!.

Directories do not have extensions because there is *no meaning* assigned to an extension in a directory's name, so whatever is at the end of it is just *not an extension*, but part of a string. Not because there is something wrong with that and it would look like a file.

.txt may have been a somewhat silly choice, but if any other dot in a directory file name can trip some program up, am I supposed to never use dots in a directory's name? I will use anything but a line break.

**Comment by mortii** [comment]
@aleksejrs we only need the file names so os.walk does indeed seem like a better choice than glob.  I'll try replacing it.

**Comment by mortii** [comment]
this now works with file structures like: `fsrs.MD/fsrs.txt/fsrs.wiki.txt`

next release is probably within a couple of days.
