### ISSUE TITLE
Remember the Readability Report Generator settings

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#147]

**Comment by mortii** [comment]
Per session or persistent between sessions too?

**Comment by aleksejrs** [comment]
I haven't considered using different frequency lists and therefore different corpora in it, so persistent.
If I do change it all the time, it will still be good if it remembers what I was looking at last time, even though I have a bookmark for the main corpus in the Open window.

**Comment by mortii** [comment]
sure, this is a nice QOL upgrade.

**Comment by mortii** [comment]
It probably makes sense to store all the settings (extensions, preprocessing, etc), and not just the input dir.

I think this makes a lot of sense of the RRG since I imagine someone might want to run it every day, but the FFG usage is probably less frequent, so I'm not sure there is much to gain with storing the previous settings for it.



Thoughts @aleksejrs ?

**Comment by aleksejrs** [comment]
Sure, all those settings are important.
I always considered readability just a nice addition to the frequency list generation. FFG has a greater impact on the learning process, so its settings seem more important, but if anybody uses the settings in RRG often, they will also want them to be consistent.

**Comment by mortii** [comment]
I'll make the RRG settings persistent first, then maybe do the same for the FFG later.

**Comment by aleksejrs** [comment]
On the other hand, the persistence of the frequency.csv file can lead to accidental overwriting if you use multiple files. A history dropdown might help.

**Comment by mortii** [comment]
> On the other hand, the persistence of the frequency.csv file can lead to accidental overwriting if you use multiple files. A history dropdown might help.

A history drop down would be overkill I think. Cool idea though.

**Comment by mortii** [comment]
The generators' settings will be very volatile for a while, so I'll wait a little longer to implement this.

**Comment by mortii** [comment]
@aleksejrs @Gardengul 

you guys want all the settings to be saved and not just the preprocessing ones, right?

**Comment by aleksejrs** [comment]
@mortii, yeah.
It seems obvious to me that the settings that are not changed every time should be saved.
* "Add occurrences column" only affects the user, and why would the user want different ones for different lists?
* "Lemma and inflection" vs "Lemma" is related to a global setting in AM (and does not depend on it), so it is unlikely to be changed. I use the default "Lemma and inflection" though.

**Comment by mortii** [comment]
@aleksejrs could you help test it?

Either pull the [extra-settings branch](https://github.com/mortii/anki-morphs/tree/extra-settings) or use [this .addon file](https://drive.google.com/file/d/1ydlF-aZCk_F5P7ye9aPHWyV8rsLIbYz5/view?usp=sharing).

**Comment by mortii** [comment]
released in [v3.1.0](https://github.com/mortii/anki-morphs/releases/tag/v3.1.0)
