### ISSUE TITLE
Unsure how to successfully move from the original Morphman add-on without losing all my progress

### ISSUE THREAD

**Issue by quietmansoath** [mortii/anki-morphs#148]
## What is the current documentation?

There is none currently.

## What changes do you suggest?

The original Morphman addon by kaegi is still functional and usable with Qt 6. I only found this add on after looking into issues with its parser, and now I would like to switch. However, I'm unsure how to do so without losing all my progress. I imagine there are other users would might have the questions I do, such as:

- Should I export all of studied and in progress words into a CSV spreadsheet?
- Should I use the same tags that I was using with Morphman with Anki Morphs?
- Should I manually delete all of the words in the morph field of my card so that Anki Morphs can cleanly reparse everything?

**Comment by aleksejrs** [comment]
> Should I manually delete all of the words in the morph field of my card so that Anki Morphs can cleanly reparse everything?

AnkiMorphs uses different extra fields, and can only work with the words in one field of the note.

I don't know what progress you are worried about losing, but you can exclude the cards sorted by MorphMan by tags. It can lead to a small bug though, if you don't do it correctly: https://github.com/mortii/anki-morphs/issues/138#issuecomment-1925733386

**Comment by mortii** [comment]
@quietmansoath that for the feedback!

These are excellent questions, I'll address them in the guide.

Like @aleksejrs mentioned, AnkiMorphs uses different extra fields. It also uses a different database, different user-files. etc, so there isn't really anything that can get lost, nor will previous MorphMan stuff interfere with AnkiMorphs.

>  Should I export all of studied and in progress words into a CSV spreadsheet?

I consider the exporting/importing of known morphs as more of a tool for trimming down your card collection if you want to do that--it's not a requirement for transitioning to AnkiMorphs.

> Should I use the same tags that I was using with Morphman with Anki Morphs?

This is actually one way you can mess up progress I guess. If you re-use the same tags from MorphMan then AnkiMorphs might update/remove them from cards as part of it's procedure. If you then find out you want to go back to MorphMan instead, then those tags could potentially cause problems for MorphMan if they are in unexpected places. So I recommend using the default AnkiMorphs tags.

> Should I manually delete all of the words in the morph field of my card so that Anki Morphs can cleanly reparse everything?

No, it doesn't matter. If you want to completely transition to AnkiMorphs then you might make your life easier if you removed the MorphMan specific fields and tags from your cards, that way there would be less clutter for you to deal with on a day to day basis.

**Comment by quietmansoath** [comment]
Thank you both! I wrote out my questions before I fully understood how the am-unknowns and other generated fields worked. 

My goal was to avoid having AnkiMorphs consider unknown words I had already studied with Morphman, so I ended up marking every sentence in the deck that had a due date with the tag I use in Morphman for already known cards, and using that same tag for the same function in Anki Morphs (I renamed the 'All Morphs Known' tag). I'm still wrapping my head around how AM works so I'm not fully sure it was necessary, but it is showing roughly about the same known words and is allowing me to keep studying those cards with their respective due dates.

Still, I appreciate you responding and adding these points to the guide!

**Comment by mortii** [comment]
> Both MorphMan and AM consider words in the chosen fields of a mature card known.

Yeah, both MorphMan and AnkiMorphs determines which morphs are known by how long the learning interval of the card is, so they should basically come to the exact same conclusion.

> My goal was to avoid having AnkiMorphs consider unknown words I had already studied with Morphman, so I ended up marking every sentence in the deck that had a due date with the tag I use in Morphman for already known cards, and using that same tag for the same function in Anki Morphs (I renamed the 'All Morphs Known' tag)

@quietmansoath This might seem weird or counter-intuitive, but having done dev work on both MorphMan and AnkiMorphs, I'm of the opinon that people (understandably) overthink tags. If you were to remove every MM and AM tag from all of your cards, it would actually not be a big deal--the appropriate tags would be applied again the next time you recalc. You will lose some known morphs, but you can very quickly get those back by using the 'K' key when you encounter them on cards.

I might even advise doing that in your case, that way you don't have to mix and match tags, which can quickly get complicated and confusing.

Sorry if all this information is overwhelming--I'm so intimately familiar with the inner workings of the add-on that I can lose perspective about it sometimes.

**Comment by quietmansoath** [comment]
@mortii  Thank you so much for your responsiveness!

I wasn't (and still am not sure) if I am ready to fully transfer to Anki Morphs, but should I do so I definitely will clean up the tags and fields I was using with Morphman only.

> Yeah, both MorphMan and AnkiMorphs determines which morphs are known by how long the learning interval of the card is, so they should basically come to the exact same conclusion.

Oh, I see. This again was likely confusion on my part then. I remember when I was setting this up in AM that I wasn't sure if I should have added a row for both my sentence fields and my morph fields. In the end I set it up to only read and modify the deck based on the sentence field. Perhaps I should have done something differently. Luckily that one tag I mentioned was the only one I'm mixing, and that seems to be working pretty well so far.

**Comment by mortii** [comment]
> I remember when I was setting this up in AM that I wasn't sure if I should have added a row for both my sentence fields and my morph fields.

That also seems like a common problem people have, so that should also be addressed in the guide. On sentence cards, one should definitely only select the field that has the sentence, not the focus morph field. The sentence has more context, which makes the analysis of the morphs better. It's very easy to get false positives when analyzing standalone single morphs.

**Comment by quietmansoath** [comment]
Oh, perfect! It sounds like I managed to set it up correctly then. Thank you for your help!

**Comment by quietmansoath** [comment]
Oh, whoops, I clicked "done" by accident, not sure if that was desired.

**Comment by mortii** [comment]
Np, I'll keep it open until I have implemented all the changes we have discussed.

**Comment by mortii** [comment]
So there are four points here that should be addressed in the guide:
1. Should I have added a row for both my sentence fields and my morph fields?
2. Should I use the same tags that I was using with Morphman with Anki Morphs?
3. Should I export all of studied and in progress words into a CSV spreadsheet?
5. Should I manually delete all of the words in the morph field of my card so that Anki Morphs can cleanly reparse everything?

I think 1 and 2 should be addressed in settings guide where appropriate, they don't even have to name MorphMan since they can apply generally.

3 and 4 is pretty specific to transitioning from MM so it might make sense to have them in a dedicated section to that. I'm thinking of adding a 'Transitioning from MorphMan' section to the [tips & tricks chapter](https://mortii.github.io/anki-morphs/user_guide/setup/tips-and-tricks.html). 

Does that sound reasonable @quietmansoath, or would you prefer it be done in a different way?

**Comment by quietmansoath** [comment]
No, that all sounds reasonable! Thank you!

**Comment by mortii** [comment]
I updated these:
- [settings: note-filter field](https://mortii.github.io/anki-morphs/user_guide/setup/settings/note-filter.html#field)
- [settings: tags](https://mortii.github.io/anki-morphs/user_guide/setup/settings/tags.html)
- [faq](https://mortii.github.io/anki-morphs/user_guide/faq.html)

the boundary between the faq section and the tips & tricks section is pretty blurry. I might merge them at some point.

Let me know if you have any more questions or suggestions!
