### ISSUE TITLE
Have AnkiMorphs prioritize longer or shorter sentences based on user setting

### ISSUE THREAD

**Issue by quietmansoath** [mortii/anki-morphs#154]
**Is your feature request related to a problem? Please describe.**
AnkiMorphs keeps giving me my shorter sentences that I didn't even realize were in my collection because Morphman allows the user to adjust sentence priority based on character length. This is done in it's config.py file and is also partially controlled by tags (I know you know this already mortii but for anyone else who might read this)

![image](https://github.com/mortii/anki-morphs/assets/46270221/9f99f7cf-a731-4ef2-a773-b9bdb199fca2) (img source, [Jo-Mako's Japanese Guide website](https://sites.google.com/view/jo-mako/readability-list/morphman#h.fm9rwx92eqh3))

**Describe the solution you'd like**
I would like a manner to tell AnkiMorphs that I want to prioritize (yes, prioritize) sentences above x amount of characters, less than y amount of characters, things like that. It would be great to be able to optionally tag them as too long or too short as well. It would probably make sense to add this somewhere more user-friendly than a config.py file, but I personally don't mind where it goes, if it's possible to add this feature.

**Describe alternatives you've considered**
I don't think there is any alternative other than using Morphman.

**Comment by quietmansoath** [comment]
Ah, actually, while this might still be useful to people, I was able to fix this by resetting my database and tags. I'm not sure what was going on before but I'm not getting only my short sentences anymore. Sorry!

**Comment by mortii** [comment]
I could write a 40-page essay about this, but I'll make TL;DR version:

I conjecture that there is no good and simple way of doing this. Any coefficients would be too subjective. It could be an interesting machine learning problem, but not one I'm interested in doing, at least not right now.

As a quick anecdote I'll say that after a certain point MorphMan would always show me sentences that were too complicated--for every single new card I would have to use `L` to find an easier one, and there almost always was an easier one.

My conjecture could be completely wrong of course. If you or anyone else provides a specific algorithm or an amendment to the [current one](https://mortii.github.io/anki-morphs/user_guide/usage/recalc.html#difficulty-algorithm) that would implement this feature, then I'll happily take a look at it.
