### ISSUE TITLE
Add info about study plan feature to the FAQ

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#156]
>After a little more thought, I have concluded that this part makes implementing a successive 'study plan' unfeasible:
>
>> Btw, the order of the chapters would have an crucial impact on the 'study plan', which adds an exponential amount of complexity to this, which I don't love.
>
>Regardless of how you do it, there is no good way set the order of the files without a significant amount of manual work, unless you are lucky and someone else has already numbered/named them in a convenient way.
>
>So the two alternatives are:
>1. Create a global frequency files of all the chapters (best for general learning)
>2. Switch between the individual frequency files of the chapters
>
>@Vilhelm-Ian  and I discussed in #114 the possibility of adding a download button next to each file in the 'frequncy file generator' to download the individual frequency files when generating a global frequency file, and I still think that is a good idea/feature.
>
>I'll add this to the FAQ.

_Originally posted by @mortii in https://github.com/mortii/anki-morphs/discussions/155#discussioncomment-8500390_

**Comment by mortii** [comment]
also: update contributors

**Comment by mortii** [comment]
and latex equations

**Comment by aleksejrs** [comment]
> Regardless of how you do it, there is no good way set the order of the files without a significant amount of manual work, unless you are lucky and someone else has already numbered/named them in a convenient way.

It happens automatically with ocrmypdf, not so hard with Vim, and simple with books or subtitles instead of chapters.

**Comment by mortii** [comment]
> It happens automatically with ocrmypdf, not so hard with Vim, and simple with books or subtitles instead of chapters.

Absolutely, anything can be trivial if you are technical enough. But for the general user that might download some files that have regular non-numbered titles of episodes or whatever, it might require significant amount of work to number them/sort them in the order they want.

I guess that is a general theme in the feature requests I turn down, I want people who are not super-amazingly technical to be able to use the add-on without too much difficulty and confusion.
