### ISSUE TITLE
Additional stats in readability

### ISSUE THREAD

**Issue by Jcuhfehl** [mortii/anki-morphs#160]
When using the readability analyzer, it feels like it's missing a few relevant stats that morphman had. The most important me is the difference between what morphman called morphs and instances. Being able to see both would be useful. Additionally, line readability and aggregate stats for all the analyzed files seem useful to me.

**Comment by mortii** [comment]
@Jcuhfehl Thanks for the feedback!

I completely agree that there should be more in-depth stats. We have discussed it in #114:

> [...] 
>2.  Add detailed reports for each entry
>
>I'm thinking we could have a column all the way to the right in this table:
![readability-report-generator-percentages](https://github.com/mortii/anki-morphs/assets/15674619/89acb318-8bb6-4455-b0d5-77f6f766de24)
>
>that has buttons that say 'detailed report' or something like that. When you click it you open a new dialog. That dialog can have have this information in separate tabs:
>
>### tab 1: fine grained morph stats
>
>
>``` text
>percentile |  morph-inflection | morph-lemma |learning status 
>0%         |   the             |  the        | known
>2%         |   a               |  a          | learning
>``` 
>  [...] 


_Originally posted by @mortii in https://github.com/mortii/anki-morphs/discussions/114#discussioncomment-8171257_

@Vilhelm-Ian do you still want to work on this? Now that we have an actual feature request we should maybe bump up its priority. I don't want to add any pressure to you, so I can contribute and help finish it faster if that would help. It would maybe take me a day or two to make this.

**Comment by mortii** [comment]
Added in [v1.3.0](https://github.com/mortii/anki-morphs/releases/tag/v1.3.0)

Thank you!
