### ISSUE TITLE
Crash when reviewing cards with Card Info open

### ISSUE THREAD

**Issue by xofm31** [mortii/anki-morphs#162]
When reviewing a card, I press "i" to open the Card Info window. If I leave that window open when I rate the card, Anki crashes every time.

I am running on a Mac. I have other add-ons as well, but if I disable Ankimorphs, the problem goes away. If you can't duplicate this, I can do more investigation to see if there is an interaction with the other add-ons.

**Comment by mortii** [comment]
@xofm31 fixed in [v1.2.4](https://github.com/mortii/anki-morphs/releases/tag/v1.2.4), thanks again!
