### ISSUE TITLE
Mismatch between morpheme and am-highlighted 

### ISSUE THREAD

**Issue by cocowash** [mortii/anki-morphs#163]
**Describe the bug**
Anki-moprhs recognizes the correct morph but fails to highlight it correctly 

**To Reproduce**
just run recalc on the current version

**Screenshots**
![01](https://github.com/mortii/anki-morphs/assets/62455662/c758b8db-4c2f-45f2-bf7e-276b92725e8f)
![Captura de pantalla 2024-02-26 120324](https://github.com/mortii/anki-morphs/assets/62455662/3adf484d-9aee-4179-a4dd-cb5a443b2458)
![02](https://github.com/mortii/anki-morphs/assets/62455662/a22e5687-76ac-4923-aa07-85828c0ff0c5)
(this is the source from which am-highlighted is getting the sentence)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Anki Version [23.12.1]
 - AnkiMorphs Version [1.2.4]

**Additional context**
I think this behavior is the result from recent updates to the plugin, I haven't changed any substantial recently.  I tried to erase am-highlighted manually to see if that would repopulate it correctly, but I hadn't a good result.  

Thanks again for sharing this add-on to the community, I really appreciate your effort.

**Comment by mortii** [comment]
ah, I forgot to specify that the regex should ignore cases. With that addition I get this:

![Screenshot from 2024-02-26 12-46-35](https://github.com/mortii/anki-morphs/assets/15674619/45ba8520-f873-4410-8338-c3657b9b9e18)

I'll push a hotfix asap!

**Comment by mortii** [comment]
Fixed in [v1.2.5](https://github.com/mortii/anki-morphs/releases/tag/v1.2.5), thanks for letting me know!
