### ISSUE TITLE
Anki freezes when AnkiMorphs updates

### ISSUE THREAD

**Issue by knoebelja** [mortii/anki-morphs#164]
**Describe the bug**
Whenever I get an update notification in Anki for AnkiMorphs, AnkiMorphs tries to update seen morphs automatically and runs forever.

**To Reproduce**
1. Open Anki when an automated update is prompted to be installed.

**Expected behavior**
Anki doesn't freeze or try to update seen morphs.

**Screenshots**
![image](https://github.com/mortii/anki-morphs/assets/16282046/7705c65f-f86c-433a-a94f-11cb39f28a62)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Anki Version: not sure... app is frozen and can't verify
 - AnkiMorphs Version: latest minus 1

**Additional context**
This happened during the last update. Killing the app and restarting it worked before, but now it's a repeated behavior.

**Comment by knoebelja** [comment]
The only way around it that I found was launching Anki with my wifi turned off. Then updating the add-on manually.

**Comment by mortii** [comment]
@knoebelja oh wow, that's horrible. I'm not sure I can repeatedly test this, which makes it extra bad.

Based solely off of your description it seems like there occurs a deadlock when both the 'update seen morphs' and the 'update add-ons' dialogs are open at the same time.

Some info about the 'update seen morphs' thing:

AnkiMorphs updates seen morphs when the profile is first loaded and after a card review is undone (Ctrl+Z). It goes through all the cards that have been studied earlier that day and determines which morphs have been seen. The more cards that have been studied, the longer this process takes, so this bug you are experiencing might be more likely if you have already used Anki previously that day.

Something you can do to potentially mitigate this:
1. Turn off wifi
2. Open Anki and let the 'update seen morphs' process finish
3. Turn on wifi
4. Run the updater by going to Tools -> Add-ons -> Check for updates

I'll look more into how I can solve this problem tomorrow. 

Sorry this happened to you!

**Comment by knoebelja** [comment]
Added context, I do my reviews on the mobile app. Not from the desktop, so that might have an impact too.

**Comment by mortii** [comment]
@knoebelja did these steps work?

>    1. Turn off wifi
>    2. Open Anki and let the 'update seen morphs' process finish
>    3. Turn on wifi
>    4. Run the updater by going to Tools -> Add-ons -> Check for updates

**Comment by mortii** [comment]
@knoebelja hopefully it is fixed after you update to [v1.2.6](https://github.com/mortii/anki-morphs/releases/tag/v1.2.6).

If it doesn't fix the problem, then just write a new comment in this issue and I'll reopen it.

Thanks for the feedback!
