### ISSUE TITLE
Latin characters causes Mecab spawning to crash on windows

### ISSUE THREAD

**Issue by Kirmassine** [mortii/anki-morphs#168]
Good morning,
This is my first time installing Ankimorph. I tried to modify the settings from the tools tab, but I am given this error message:

line 139, in spawn_mecab
     "^bos-feature: (.*)$", str(config_dump, "utf-8"), flags=re.M
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 122: invalid continuation byte

I'm on Windows 11, with Anki version 2.1.50-23.12.1 and the latest Ankimorphs update.

**Comment by mortii** [comment]
@Kirmassine Thanks for letting me know!

When exactly does the error occur? When you click the 'save' button?

**Comment by Kirmassine** [comment]
This happens when I press the settings button, in the tools tab. I can't even reach the settings window. 
![Capture d'écran 2024-03-02 111623](https://github.com/mortii/anki-morphs/assets/145543550/574cda3d-90d9-4242-adaf-44cd1aee4d5e)

**Comment by mortii** [comment]
@Kirmassine very weird. 

Acoording to [this site](https://bytetool.web.app/en/ascii/code/0xee/) to It looks like `byte 0xee` is the character `î`. 

The path to the add-on is this on windows:
```
Windows: C:\Users\[user]\AppData\Roaming\Anki2\[profile_name]
```

What are the names of your [user] and [profile_name] folders? Do they contain latin characters or some other non-utf8 characters by chance?

**Comment by Kirmassine** [comment]
My name is Benoît, with an î. If I understand correctly, then this would be a problem due to my name?

**Comment by mortii** [comment]
> My name is Benoît, with an î. If I understand correctly, then this would be a problem due to my name?

Yes. Maybe I can fix it accept latin characters too, but I'm not sure if that is possible without making characters from other languages break instead.

**Comment by mortii** [comment]
@Kirmassine trying to fix this bug is truly a nightmare since testing it requires a lot of setup. 

Could you do me a favor and do the following:
1. Open up a command prompt and write: `chcp`
2. Take a screenshot of the command prompt and upload it here

**Comment by Kirmassine** [comment]
I don't know much about computers (and I'm bad in english), so I don't know if that's what you're asking. If not, sorry and can you elaborate more on what you want? I absolutely don't mind helping you :)

![image](https://github.com/mortii/anki-morphs/assets/145543550/dcccc668-a0e3-4d35-8ee8-b928f410ee67)

**Comment by mortii** [comment]
@Kirmassine perfect picture, thank you :+1: 

It says `C:\Users\TEMP`, is that the user you are using Anki on? I expected to see `C:\Users\Benoît`. Knowing the exact username would help me debug the problem better.

**Comment by Kirmassine** [comment]
I don't give the same username than before, because I was trying to change it. It didn't work too well at first, but I solved all my problems. The addon works now, just by changing the î to i.

My old username was "C:\Users\lastname Benoît". Since it had my last name, I don't want to give it. But I can tell  that there were only alphabetic latin characters, without any particular diacritic (no è, é, ï, î etc.).

**Comment by mortii** [comment]
> I don't give the same username than before, because I was trying to change it. It didn't work too well at first, but I solved all my problems. The addon works now, just by changing the î to i.

@Kirmassine I'm glad you made it work!

> My old username was "C:\Users\lastname Benoît". Since it had my last name, I don't want to give it. But I can tell that there were only alphabetic latin characters, without any particular diacritic (no è, é, ï, î etc.).

Ah, I see, completely understandable. Thanks for clarifying and giving me the info I wanted. I'm going to try fixing this bug so people don't have to change their username, but this bug is very specific and very complicated, so it might take a while.

**Comment by Kirmassine** [comment]
Good luck and thank you for this wonderful addon !

**Comment by mortii** [comment]
this will be left as a known problem, apologies.
