### ISSUE TITLE
Add warning when recalc is going to require full upload

### ISSUE THREAD

**Issue by xofm31** [mortii/anki-morphs#170]
When Ankimorphs creates new fields on cards for the first time, the next sync will require a full upload, and overwrite any modifications to cards done elsewhere.

Another add-on (Remove Card History) gives a helpful warning before making the change. 

> The requested change will require a full upload of the database when you next synchronize your collection. If you have reviews or other changes waiting on another device that haven't been synchronized here yet, they will be lost. Continue?

**Comment by mortii** [comment]
Good idea!

**Comment by mortii** [comment]
Is this message okay?
```
Additional "extra fields" have been selected in the settings, which might cause
a full upload of your card collection the next time you synchronize. Any reviews
or changes that have been made on other devices will be lost when a full upload
takes place. Do you still want to continue?
```

**Comment by xofm31** [comment]
That's good.

**Comment by mortii** [comment]
coming shortly
