### ISSUE TITLE
Add window controls to windows

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#173]
**Is your feature request related to a problem? Please describe.**
Readability Analyzer shows a table that need the window to be enlarged.

**Describe the solution you'd like**
All windows that contain big stuff should have a maximize button.
All windows that do not block Anki should have a minimize button.

**Comment by mortii** [comment]
Oh yeah, I've had this in idea in the back of my mind for ever, I just haven't gotten around to it. IIRC it requires changing the class from a 'dialog' to a 'main window'. The last time I looked into it I found that the anki 'Browse' window was a good example of how to do this.

**Comment by mortii** [comment]
This will be included in the next release.
