### ISSUE TITLE
Shortcut to mark word as proper noun instead of known

### ISSUE THREAD

**Issue by knoebelja** [mortii/anki-morphs#177]
**Is your feature request related to a problem? Please describe.**
Im marking proper nouns as known words and it affects my word count. Id like to be able to mark them as names or something so I can add them to morphs without affecting word count. 

Thanks for fixing the syncing bug!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mortii** [comment]
There is already a feature for that: https://mortii.github.io/anki-morphs/user_guide/setup/names.html

select/highlight the proper noun -> right click -> Mark as name

Correct me if you meant something else :)

**Comment by knoebelja** [comment]
I meant a short cut for when you are doing your actual new cards. So when it shows you something that it recognized as a new word, you can do like ctrl+P instead of ctrl+k and it marks that llema as a name instead of known.

**Comment by knoebelja** [comment]
But that works! Thank you

**Comment by mortii** [comment]
> I meant a short cut for when you are doing your actual new cards. So when it shows you something that it recognized as a new word, you can do like ctrl+P instead of ctrl+k and it marks that llema as a name instead of known.

That's reasonable, we could probably extend the "mark as name" feature to do it's thing when you press a keyboard shortcut.

Note to self:
- Maybe use a scroll view in the "shortcuts" settings tab to make the minimum size smaller

**Comment by mortii** [comment]
[Not adding any new features](https://github.com/mortii/anki-morphs/releases/tag/v3.3.0), apologies.
