### ISSUE TITLE
Add dropdown to find a highlighted word in am-morphs when studying

### ISSUE THREAD

**Issue by xofm31** [mortii/anki-morphs#187]
When I am studying my sentence cards, I sometimes forget other morphs that aren't the one that I have the definition for on that card. I would like to be able to highlight the morph on the card, and have it find the card that has that highlighted text as the am-unknowns. I threw this together in the __init__.py, and it almost works. It does look for the highlighted text, but it does it before you get to the dropdown.

Hopefully you like this feature, or have a better suggestion on how to easily find the definition for a morph that is not the am-morphs on that card. 

```
def search_am_unknowns_action(web_view: AnkiWebView, menu: QMenu) -> None:
    assert mw is not None
    selected_text = web_view.selectedText()
    if selected_text == "":
        return
    action = QAction(f'Find in {ankimorphs_globals.EXTRA_FIELD_UNKNOWNS}', menu)
    query = f'"{ankimorphs_globals.EXTRA_FIELD_UNKNOWNS}:{selected_text}"'
    browser = aqt.dialogs.open("Browser", mw)
    assert browser is not None

    search_edit: Optional[QLineEdit] = browser.form.searchEdit.lineEdit()
    assert search_edit is not None

    search_edit.setText(query)
    browser.onSearchActivated()
    menu.addAction(action)
```

**Comment by mortii** [comment]
Ah, you basically almost made the "browse same morph" feature you described in #181. The way it gets around the problem of having too many keyboard shortcuts is very clever, I like it!

It might need a little tweaking, but if you create a pull request we can discuss/work on it there, and we could possibly include it in the v1.4 update.

**Comment by xofm31** [comment]
> Ah, you basically almost made the "browse same morph" feature you described in https://github.com/mortii/anki-morphs/discussions/181.

It's not quite the same, because here, the purpose is to find card(s) that have already been learned, so no need to search for cards that have multiple unknowns. But yes, very similar.

> It might need a little tweaking

You are very generous. It actually doesn't work. But I will create a pull request.

**Comment by mortii** [comment]
I've merged it into main: https://github.com/mortii/anki-morphs/commit/e0ccf25eddbbb4e1fc25144c6d73ddb925dd4a7e 
It will be included in the next update.
Thanks!

**Comment by mortii** [comment]
@xofm31 any suggestions for where to place this in the guide?

**Comment by xofm31** [comment]
Thank you for getting this in!

Since it is not a critical function, and its meaning is so clear, maybe you don't need to put it in the guide?

If you want to include it, I guess it would go under https://mortii.github.io/anki-morphs/user_guide/usage/reviewing-cards.html. In that case, I'd have a section for the dropdown & also include the marking a Name.

**Comment by mortii** [comment]
> If you want to include it, I guess it would go under https://mortii.github.io/anki-morphs/user_guide/usage/reviewing-cards.html. In that case, I'd have a section for the dropdown & also include the marking a Name.

Great idea, I'll do that.

Btw, I just realized why I haven't seen dynamic labels in the context menu other places:
![wide](https://github.com/mortii/anki-morphs/assets/15674619/7df54383-35f9-43e5-ad47-0fa42a492ea2)

so, I'll revert them back to being static

**Comment by xofm31** [comment]
I didn't think of that.

I don't have an opinion about the dynamic labels, but if you wanted to keep them, you could check the length of the highlighted text, and if it's more than a certain length (5? 10? 20?), you could either get rid of it, or shorten it. (Browse "am-unknowns:teach...").

**Comment by mortii** [comment]
> I don't have an opinion about the dynamic labels, but if you wanted to keep them, you could check the length of the highlighted text, and if it's more than a certain length (5? 10? 20?), you could either get rid of it, or shorten it. (Browse "am-unknowns:teach...").

I thought about that, but clipping the text would make it lose much of its purpose, which was to display exactly the text that would be used, so I'll just go back to completely static.
