### ISSUE TITLE
[Add-on Startup Failed] ModuleNotFoundError: No module named 'PyQt6'

### ISSUE THREAD

**Issue by pallas42** [mortii/anki-morphs#188]
**Describe the bug**
AnkiMorphs Add-on Startup Failed

**To Reproduce**
1. Install ankimorphs addon by pasting the code 472573498
2. quit anki
3. restart anki
4. pop-up error message

**Expected behavior**
ankimorphs addon functioning smoothly

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS-10.15.7-x86_64-i386-64bit
 - Anki Version: 23.12.1
 - AnkiMorphs Version  latest : Updated 2024-03-10

**Additional context**
The Anki Debug Info is attached as follows:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-10.15.7-x86_64-i386-64bit

When loading AnkiMorphs:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/me/Library/Application Support/Anki2/addons21/472573498/__init__.py", line 38, in <module>
    from . import (
  File "/Users/pallas/Library/Application Support/Anki2/addons21/472573498/browser_utils.py", line 21, in <module>
    from .ui.view_morphs_dialog_ui import Ui_ViewMorphsDialog
  File "/Users/me/Library/Application Support/Anki2/addons21/472573498/ui/view_morphs_dialog_ui.py", line 9, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt6'

**Comment by mortii** [comment]
> Python 3.9.15 Qt 5.14.2 PyQt 5.14.1

Sorry, I forgot to mention in the description on ankiweb that AnkiMorphs only works on Anki Qt6, not Anki Qt5.

I mentioned why we don't support Qt 5 here: https://mortii.github.io/anki-morphs/user_guide/faq.html#can-you-make-ankimorphs-work-on-anki-qt5

I've updated the description now. Thanks for the feedback!
