### ISSUE TITLE
Suspend Short Sentences

### ISSUE THREAD

**Issue by Pedrubik2000** [mortii/anki-morphs#195]
# Feature Request:

1. **Prioritize Longer Sentences**: Implement a feature that allows AnkiMorph to prioritize sentences with more words. This prioritization will ensure that users are exposed to longer, more complex sentence structures, which can be beneficial for language acquisition.
2. **Suspend Short Sentences**: Introduce functionality that automatically suspends sentences that are too short. Short sentences may not provide sufficient context or challenge for language learners. Suspending them will enable users to focus on sentences that offer greater linguistic complexity and depth.

# Expected Behavior:

- Users should have the option to enable or disable prioritization of longer sentences.
- AnkiMorph should suspend sentences below a user-defined threshold of minimum words.
- The feature should be configurable to accommodate varying preferences and learning goals.

**Comment by Vilhelm-Ian** [comment]
Already being discussed at #191

**Comment by mortii** [comment]
@Pedrubik2000 Thanks for the suggestions!

> 1. Prioritize Longer Sentences: Implement a feature that allows AnkiMorph to prioritize sentences with more words. This prioritization will ensure that users are exposed to longer, more complex sentence structures, which can be beneficial for language acquisition.

Like @Vilhelm-Ian mentioned, this is feature is being discussed in #191, feel free to chime in there if you want :)

> 2. Suspend Short Sentences: Introduce functionality that automatically suspends sentences that are too short. Short sentences may not provide sufficient context or challenge for language learners. Suspending them will enable users to focus on sentences that offer greater linguistic complexity and depth.

Where would you want that feature? In the Recalc settings? A separate window like the [known morphs exporter](https://mortii.github.io/anki-morphs/user_guide/usage/known-morphs-exporter.html)?

**Comment by mortii** [comment]
It just occurred to me that we could add a new extra field called `am-total-morphs-count` which then can be used for sorting in the browse window and people can then easily suspend/delete those cards if they want. That is a cleaner approach than having a dedicated option for something like this.

**Comment by Pedrubik2000** [comment]
> @Pedrubik2000 Thanks for the suggestions!
> 
> > 1. Prioritize Longer Sentences: Implement a feature that allows AnkiMorph to prioritize sentences with more words. This prioritization will ensure that users are exposed to longer, more complex sentence structures, which can be beneficial for language acquisition.
> 
> Like @Vilhelm-Ian mentioned, this is feature is being discussed in #191, feel free to chime in there if you want :)
> 
> > 2. Suspend Short Sentences: Introduce functionality that automatically suspends sentences that are too short. Short sentences may not provide sufficient context or challenge for language learners. Suspending them will enable users to focus on sentences that offer greater linguistic complexity and depth.
> 
> Where would you want that feature? In the Recalc settings? A separate window like the [known morphs exporter](https://mortii.github.io/anki-morphs/user_guide/usage/known-morphs-exporter.html)?

Yes, I would like it in tha Recalc settings but a separate window would be okay too.

**Comment by Pedrubik2000** [comment]
> It just occurred to me that we could add a new extra field called `am-total-morphs-count` which then can be used for sorting in the browse window and people can then easily suspend/delete those cards if they want. That is a cleaner approach than having a dedicated option for something like this.

Yeah, this could work too. Nice idea

**Comment by mortii** [comment]
This is included in the v3 update: https://github.com/mortii/anki-morphs/releases/tag/v3.0.0

Thanks!
