### ISSUE TITLE
cards with zero uknown morphs sorting to the front of the deck

### ISSUE THREAD

**Issue by fuquasteve** [mortii/anki-morphs#196]
When I run recalc, the cards which have no unknown morphs are sorted to the front of the deck.  I just upgraded.

Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.11.7 Qt 6.6.2 PyQt 6.6.1
Take a large collection of cards (100000 in my case) and set the program to skip cards.

I would expect the cards to sort with the cards that have 1 uknown to come first in the deck.  Instead I get cards with no unknown morphs.

Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.11.7 Qt 6.6.2 PyQt 6.6.1
 - AnkiMorphs Version (I am embarassed, but I don't see where to get the vesion.  It is what I just updated in the last hour or so.)
 - Manjaro Linux
 -

**Comment by fuquasteve** [comment]
I read through the configuration and  I didn't notice any difference that would effect this behavior.  Perhaps I missed something.

**Comment by mortii** [comment]
> AnkiMorphs Version (I am embarassed, but I don't see where to get the vesion. It is what I just updated in the last hour or so.)

Oops, I forgot to add that to the template. It's found on the bottom of the AnkiMorphs settings windows:

![Screenshot from 2024-03-24 10-31-41](https://github.com/mortii/anki-morphs/assets/15674619/d039b7c4-4a6f-4364-b978-c918568808f3)

I mentioned this in the [v2.0.0 release notes/changelog](https://github.com/mortii/anki-morphs/releases/tag/v2.0.0):
> ### Move new cards that only have known morphs to the end of the due queue
> ![image](https://github.com/mortii/anki-morphs/assets/15674619/9e8f924c-3add-4b99-a5d1-04d40a54e235)
> This is now a new option in the `Recalc Settings` instead of being a hidden side effect of the `skip cards with only known morphs` option.

does it work like it used to when you select that option?

**Comment by fuquasteve** [comment]
It works as I expected now.  I noticed the changelog, but I failed to notice the new option.

It was my error.

I should have waited until after rereading in the morning to do a bug report  :-(

Sorry.

**Comment by mortii** [comment]
No problem, over-reporting is better than under-reporting :)

Thanks for letting me know that the issue templates are lacking, I'll update them soon.
