### ISSUE TITLE
Ignore this symbol »

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#20]
» this symbol is used as " in german. But anki-morphs detects it as being part of the word

**Comment by mortii** [comment]
Aah, I'll try add it asap!

**Comment by mortii** [comment]
> » this symbol is used as " in german. But anki-morphs detects it as being part of the word

Do you have a specific example, or a card id?

When I try it on your cards I get stuff like this:
>expression: «»Das weiß ich«, sagte Professor McGonagall gereizt
>morphs: das, weiß, ich, sagte, professor, mcgonagall, gereizt

which seems to be correct?

**Comment by mortii** [comment]
Ah, I found one:
> expression: «33»Sir, ich
>morph: »sir

**Comment by Vilhelm-Ian** [comment]
»Was ist los?«Harry schüttelte den Kopf und spähte durch die Bäume hinüber zuder Stelle, wo er etwas gesehen hatte

Here is a different one

**Comment by mortii** [comment]
Should be fixed now. Revive the issue if it's still a problem.
