### ISSUE TITLE
Add statistics of learned morphs

### ISSUE THREAD

**Issue by Egoistically** [mortii/anki-morphs#202]
When opening advanced statistics of a deck, MorphMan displays learned morphs over time in graphs (one for unique, and another for variations). I'd greatly appreciate if you'd consider adding this functionality. 

Here's a screenshot: https://i.imgur.com/LZzcfbh.png

(Btw, I searched just to make sure I wasn't missing it in some way, but found nothing).

Thanks a lot for your work and sorry for not following the template, I felt like it kind of didn't fit in this case.

**Comment by mortii** [comment]
I tried really hard to replicate it (#64), but it's basically impossible to do without using the deprecated API, sorry :(

**Comment by Egoistically** [comment]
Ah, that's too sad, thanks a lot though!
