### ISSUE TITLE
Study Plan generator sorts files by name, not by full path

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#206]
### Describe the bug

/directory/subdir01/k-file.txt
/directory/subdir02/a-file.txt

a-file is listed first. It should be listed second.

### My setup

 - Operating System: Debian GNU/Linux
 - Anki Version: 24.04
 - AnkiMorphs Version: v2.2.0

**Comment by aleksejrs** [comment]
Oh, it depends on how the user sorts the table.

**Comment by mortii** [comment]
Ah, I didn't really test for that.

The tables only sort the file name not the directories, which it should maybe do first... I'll look into it.

Also, the file name column in the study plan should use the path not just the file name, I'll add that too.

**Comment by aleksejrs** [comment]
The File column actually contains paths, so it can sort by directory. It's just when I tried it first before clicking the table that it was by name.

**Comment by mortii** [comment]
Oh, it does sort by directory when clicking the headers, but not when they are first loaded. That is a little weird, but not the end of the world I guess.

I'll make it so the column in the output file also contains the relative path:
![Screenshot from 2024-04-03 21-18-52](https://github.com/mortii/anki-morphs/assets/15674619/e2ebb819-d0e5-41a6-a5f0-7b5b368b3d75)

**Comment by mortii** [comment]
Should be fixed now, I'll release it shortly. Thanks!
