### ISSUE TITLE
Known morphs are not being skipped

### ISSUE THREAD

**Issue by jsteel44** [mortii/anki-morphs#207]
### Describe the bug

I'm recently finding it's showing me cards with all known morphs

[//]: # (Please provide a clear and concise description of what the bug is.)

New card is "Expression: 町", I look at my previously reviewed cards and find one with this word already (3 month interval, ie known).

### Steps to reproduce the behavior

I check AnkiMorph settings to make sure the card type is read with the correct field, everything looks fine from there. Reset default settings and set AnkiMorph up again being 100% sure the correct card types and fields are set, same issue. Skip options are all checked.

### Expected behavior

Cards with known morphs should be skipped, I'm sure this was working but maybe an update in recent weeks/months has broken this for me.

### My setup

[//]: # (Note: the AnkiMorphs version is found on the bottom of the AnkiMorphs settings window)

 - Operating System: Linux
 - Anki Version: ⁨23.12.1 (Python 3.11.8 Qt 6.6.3 PyQt 6.6.1)
 - AnkiMorphs Version: 2.2.0

**Comment by mortii** [comment]
@jsteel44 Thank you for the feedback!

In [v2.0.0](https://github.com/mortii/anki-morphs/releases/tag/v2.0.0), I added the option: "Move new cards that only have known morphs to the end of the due queue", which previously was a hidden side effect when selecting the "Skip cards with only known morphs". I have a suspicion that the previously hidden side effect was the only reason that the option worked in the first place, and now it just does nothing... I'll look into it!

**Comment by mortii** [comment]
Should be fixed in [v2.2.1](https://github.com/mortii/anki-morphs/releases/tag/v2.2.1).

Thanks!
