### ISSUE TITLE
option to remove tags that ankimorphs uses.

### ISSUE THREAD

**Issue by fuquasteve** [mortii/anki-morphs#209]
### Is your feature request related to a problem?

As part of a clumsy attempt to fix a messed up anki deck, that was showing nonsensical results, I ran the wrong morphemizer on my deck, which found zero morphs in the deck and which tagged every single card with am-known-automatically.
This produced results where ankimorphs claimed that I knew 19000 morphs, which is not the case.

### Describe the solution you would like

I would like a way to remove tags that ankimorphs uses if the user messes them up

### Describe alternatives you've considered

an option to remove all of the tags would be nice

### Additional context

My deck is huge and highlighting and removing the tags manually is very slow

**Comment by mortii** [comment]
Sure, we could add a "Remove all AnkiMorphs tags from all cards" option. Where would you want it?

**Comment by fuquasteve** [comment]
Maybe next to the restore defaults button.
Or perhaps on the ankimorph tags page.

**Comment by fuquasteve** [comment]
Do the ankimorph fields need to be cleared too to recover from running the
wrong morphemizer?
I don't think so...

**Comment by xofm31** [comment]
I have been tripped up by the tags several times, and now that I know it, I just delete the tags. But the first time, I was certain there was something wrong with AnkiMorphs. So I would suggest that whenever somebody does something likely to cause an issue (such as changing the morphemizer), either asking the user if they want to delete the tags, or at least giving a suggestion to do so. Also, if you create an option to remove the tags, I'd label it as something that might help if you feel that AnkiMorphs has messed up your known morphs. Or highlight it in your user guide.

**Comment by mortii** [comment]
>Do the ankimorph fields need to be cleared too to recover from running the
wrong morphemizer?

@fuquasteve no, shouldn't be necessary. 

> I would suggest that whenever somebody does something likely to cause an issue (such as changing the morphemizer), either asking the user if they want to delete the tags, or at least giving a suggestion to do so.

@xofm31 great idea. Implementing that could get really messy, but I will definitely keep it in mind.

> Also, if you create an option to remove the tags, I'd label it as something that might help if you feel that AnkiMorphs has messed up your known morphs. Or highlight it in your user guide.

For sure. I might make a new dialog for resetting stuff to provide more granular options, but I'm haven't decided yet.

**Comment by mortii** [comment]
This is included in the v3 update: https://github.com/mortii/anki-morphs/releases/tag/v3.0.0

Thanks!
