### ISSUE TITLE
The "Cancel" button in Settings is confusing.

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#212]
### Describe the bug

The Save button saves, but does not close the window. You have to press Cancel to close the window. It does not undo what you saved.
However, it does reject any changes you didn't save, so just renaming it to Close might not be perfect.
Maybe making Save close the window would make it less confusing.

### My setup

 - AnkiMorphs Version: 2.2.2

**Comment by mortii** [comment]
You're right, it is pretty confusing... we could potentially enable/disable it based on if any changes have been made, would that be better?

**Comment by mortii** [comment]
The future implementation is described here: https://github.com/mortii/anki-morphs/discussions/218#discussioncomment-9109229, so I'll close this issue.
