### ISSUE TITLE
Add link to "(none) note filter" error message

### ISSUE THREAD

**Issue by BobvanSchendel** [mortii/anki-morphs#227]
### Describe the bug

[//]: # (Please provide a clear and concise description of what the bug is.)
I have used anki-morphs before and it works well. Today I using a new laptop with an older version of my deck. Uninstalled MorphMan (which was still installed there), installed Ankimorphs and tried to recalc and was hit by the error message:
"Found a note filter containing a "(none)" option. Please select something else"
I don't think I changed anything about my deck other than deleting a few random cards so I'm not sure what to do about this.
I can't find anything in the documentation or open issues about this so probably just need to be pointed in the right direction.

### Steps to reproduce the behavior

[//]: # (Example:)
[//]: # (1. Go to '...')
[//]: # (2. Click on '....')
[//]: # (3. Scroll down to '....')
[//]: # (4. See error)

### Expected behavior

[//]: # (Please provide a clear and concise description of what would expected to happen instead.)

### Screenshots

[//]: # (If applicable, add screenshots to help explain your problem, otherwise you can delete this section.)

### My setup

[//]: # (Note: the AnkiMorphs version is found on the bottom of the AnkiMorphs settings window)

[//]: # (Example:)
[//]: # (- Operating System: Windows 11)
[//]: # (- Anki Version: 23.12.1)
[//]: # (- AnkiMorphs Version: v2.0.0)

 - Operating System:
 - Anki Version:
 - AnkiMorphs Version:

### Additional context

[//]: # (Add any additional context about the problem here, or delete this section if it's empty)

**Comment by mortii** [comment]
Could you upload a picture of your note filters? Like this:

![image](https://github.com/mortii/anki-morphs/assets/15674619/e2791da9-2928-4195-a66f-1199dc2489ce)

**Comment by BobvanSchendel** [comment]
Turned out I had a note filter with "None" as the notetype as I didn't change them after uninstalling morphman and installing anki-morphs. I just changed it to a valid card type and it works just fine. My bad.

**Comment by mortii** [comment]
@BobvanSchendel do you have a suggestion for a better error message? You are probably not the only one who found/will find it confusing.

**Comment by BobvanSchendel** [comment]
I think the error message itself is fine, it just stems from me not realizing what note filters actuslly are. You could add a reference to this page (https://mortii.github.io/anki-morphs/user_guide/setup/settings/note-filter.html?highlight=Note%20filter#note-filter) to the error maybe?

**Comment by mortii** [comment]
This is now included in the v3 update: https://github.com/mortii/anki-morphs/releases/tag/v3.0.0

Thanks!
