### ISSUE TITLE
new cards with Cyrillic words are am-known-automatically

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#229]
### Describe the bug

Recalc marks all new cards with only Cyrillic words "am-known-automatically".

### Steps to reproduce the behavior

1. Create a card with "йцук олдж" in the field.
2. Enable "Skip cards with only known morphs".
3. Recalc. The card tagged with "am-known-automatically".
5. Try to review. The cards is skipped.

### My setup

AnkiMorphs 2.2.4

Anki on Linux
Version ⁨24.04.2 (a1fa865b)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

**Comment by mortii** [comment]
I can't reproduce this problem. It works fine for me with both the "spaCy: ru_core_news_sm" and "AnkiMorphs: Langauge w/ Spaces".

Are you able to reproduce it with a fresh profile?

**Comment by aleksejrs** [comment]
I haven't tried yet, but I noticed that disabling "Skip cards with only known morphs" and unburying the cards may not be enough after AM has tagged the cards with am-known-automatically.

**Comment by mortii** [comment]
> I haven't tried yet, but I noticed that disabling "Skip cards with only known morphs" and unburying the cards may not be enough after AM has tagged the cards with am-known-automatically: the cards get buried again.

I can't reproduce that either, it works fine for me.
