### ISSUE TITLE
Fresh vocab note TAG request

### ISSUE THREAD

**Issue by khanguyenwk** [mortii/anki-morphs#235]
Hello, 
I have been using Morphman for the last 2 years and it's been very useful in my language learning journey with Anki. When I hear about Ankimorph I feel very happy to continue to enjoy the same feature it brings to me and at the same time get many new features and great support. For example the ability to add many morphemizers that the last one doesn't have (English, Korean, ...) 

### Is your feature request related to a problem?
No really a problem

### Describe the solution you would like

There one thing from the last one that Ankimorph doesn't have is that in the Tag Setting have this:
Fresh vocab note: Note that contains no unknown Morphs, but one or more unmature Morphs. (consider 0.5T in Morphman)

This would be helpful sometime for me when I just learn a few new cards with new morph, then after that I run Recalc to find the same cards (in other deck) that share the same new morph I learned today, then learn again through other deck to reinforce the new word's memory.

I hope you can add this to the new update, thank you so much

**Comment by mortii** [comment]
@khanguyenwk thanks for the suggestion! 

That's definitely seems like a valid use case. Would the tag "am-fresh-morph" be okay?

**Comment by khanguyenwk** [comment]
> @khanguyenwk thanks for the suggestion!
> 
> That's definitely seems like a valid use case. Would the tag "am-fresh-morph" be okay?

That's perfect, thank you so much for the very quick response~

**Comment by mortii** [comment]
Released in v3: https://github.com/mortii/anki-morphs/releases/tag/v3.0.0

Thanks!
