### ISSUE TITLE
words separated by <br> are joined

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#241]
### Describe the bug

![AMBR](https://github.com/mortii/anki-morphs/assets/1025861/b32c067d-a8f1-414d-af67-ae803b097da3)

### My system

 - Operating System: Debian GNU/Linux
 - Anki Version: 24.06 (bd88d153)⁩
 - AnkiMorphs Version: v2.2.5

### Additional context

IIRC, I had thought MorphMan got plain text from Anki, which did not contain the `<br>`. But somebody said (about a later version) that the problem was in the regexp.
FrequencyMan removes the HTML code itself; the dev just forgot to include `<br>` in the list of tags to replace with a space: https://github.com/Rct567/FrequencyMan/issues/6

**Comment by mortii** [comment]
Yep, this is known (#124).

There is a `Morphs don't split on punctuation marks` section in [known problems](https://mortii.github.io/anki-morphs/user_guide/known-problems.html) with how to fix it. That one-time fix is much better than stripping the text on every recalc imo.

Thanks for the heads up though, appreciate it :+1:

**Comment by aleksejrs** [comment]
These pages suggest using it for poems and addresses (with no extra spaces):
https://www.w3.org/TR/2011/WD-html5-author-20110809/the-br-element.html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br
https://www.w3schools.com/tags/tag_br.asp

Pressing Enter in the note editor adds a `<br>` (at least unless you do after a div or an HTML list).
[movies2anki](https://github.com/kelciour/movies2anki) turns line breaks in subtitles into `<br>` and/or joins lines with it.

The lines do not always end in a period, so a user capable of pressing Enter or using movies2anki needs careful use of regular expressions to fix it.

**Comment by mortii** [comment]
The issue is that \<br> is relatively rare, so checking and/or substituting for it potentially hundreds of thousands of times every recalc is super inefficient. Using the native search and replace feature is much better imo.

> The lines do not always end in a period, so a user capable of pressing Enter or using movies2anki needs careful use of regular expressions to fix it.

That's true, I'll update the header in the guide to something more generic.

**Comment by mortii** [comment]
I change the section in [known problems](https://mortii.github.io/anki-morphs/user_guide/known-problems.html) to "Morphs don't split correctly", and I changed the find and replace terms to make them more generic. 

Let me know if it doesn't work :)
