### ISSUE TITLE
Calculate known morphs by language (or note type, or deck)

### ISSUE THREAD

**Issue by szalejot** [mortii/anki-morphs#242]
### Is your feature request related to a problem?

I am studying multiple languages in Anki. Currently add-on shows only sum of all known morphs for the whole collection.

### Describe the solution you would like

Calculate known morphs by language, or note type, or deck. Generally provide a way to calculate known morphs only for the selected part of the collection.

**Comment by mortii** [comment]
Thanks for the suggestion!

How about a separate "stats" windows that showed more granular stats like that? I kinda like the U and A numbers being the sums of whole collection.

**Comment by szalejot** [comment]
Yes, that will also be an improvement from my perspective. 
My main pain point currently is lack of tool to easy track the progress for each language.

**Comment by mortii** [comment]
> My main pain point currently is lack of tool to easy track the progress for each language.

Understandable. One alternative is to use different anki profiles, one for each language. 

I think doing stats for note types or decks can be done without making any changes to the database, but doing it by language would probably require a significant rewrite.

I probably won't have time to implement this for many, many months, sorry about that :pray:

**Comment by mortii** [comment]
[Not adding any new features](https://github.com/mortii/anki-morphs/releases/tag/v3.3.0), apologies.
