### ISSUE TITLE
Semi-automated generation of pre-configured frequency lists and study plans

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#248]
AM supports multiple frequency lists/study plans, so they sometimes need to be generated repeatedly.
The use of the Generators window is currently complicated: you have to remember to click `Load Files` if you changed the corpus folder (takes no time with 65 MB here), then press the Generate button and edit the output file name (the "Select folder" button doesn't work for me, but I don't use it).
I would like an easier way to repeatedly generate lists from specific corpus directories and save them to specific file names.

*The rest of this section is just reasoning about why I need many lists.*

I switched to [FrequencyMan](https://github.com/Rct567/FrequencyMan), but I still generate frequency lists and study plans using AM.

FM has this feature:

> - `lexical_underexposure`: Promotes cards with high-frequency words that you are not yet proportionally familiar with. Basically, _lexical_underexposure = (word_frequency-word_familiarity)_. Increasing this value means you will be 'pushed' forward more in your language learning journey (and the word frequency list). Increase the value slightly if you experience too much overlap and not enough new words.

It also supports multiple frequency lists per target language (basically the set of morphs to be considered for a set of fields of a set of notes) and seems to choose for each word the highest frequency among the lists.

So I **guess** frequency lists may be better with FM than study plans, unless I increase `lexical_underexposure` a lot. I made the following directory structure and generated a frequency list for each of the directories:

```
English/
   nonimportant urgent/
      important nonurgent/
         important urgent/
          very important/
```

There may be quirks like precision, but a word important for the more important texts will be prioritized like a word important on average (or for long texts).
Either way, whether I use only frequency lists or also study plans (as I keep doing), going through the GUI to generate them is harder than just generating a study plan.

### Describe the solution you would like

A GUI like that for Note Filters, but with buttons to generate the list on each row.

columns:
* dropdown: type (Frequency List / Study Plan)
* text: corpus folder
* text: list file name, with or without a full path (FM supports symbolic links)
* button: generate file
* button: generate readability report

I guess file formats should also be (a) column(s), though I'd merge `.srt` and `.vtt` as subtitles, and `.txt` and `.md` as text files.
I avoided using the Tags field because I have too many tags for that, so I am not sure about all the "ignore" options.

To use this window, you would first specify the settings, which will be saved.
Then, whenever you need to update a list or see a readability report, just click the relevant button.

**Comment by mortii** [comment]
> The use of the Generators window is currently complicated

Sorry, but I think those changes this would make it more complicated, not less.

>The rest of this section is just reasoning about why I need many lists.
>I switched to [FrequencyMan](https://github.com/Rct567/FrequencyMan), but I still generate frequency lists and study plans using AM.

If you want these changes because it would make your FrequencyMan experience better, then it would be more appropriate to make the request over there.
