### ISSUE TITLE
Improve visual cues in the generator window

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#249]

**Comment by mortii** [comment]
The relevant settings being file formats?

**Comment by aleksejrs** [comment]
Whatever setting you need to click Load Files after?
So Folder and file formats sure, if nothing else affects how they are loaded.

**Comment by mortii** [comment]
That would be disastrously bad if you have a large file tree. Say you have 1M files under a directory, if you want to unselect three file formats, you would then needlessly reload millions of files...

Loading the files at your own discretion is generally much preferable, in my opinion.

**Comment by aleksejrs** [comment]
*I* don't use any of the checkboxes. I just use Select Folder and forget to click Load Files.

**Comment by aleksejrs** [comment]
Maybe make the button red/orange when the files were loaded with different settings?

**Comment by mortii** [comment]
>Maybe make the button red/orange when the files were not loaded with the current settings?

Giving more visual cues is a good idea. It might be sufficient to just disable/enable the button.

>And since the button will become more prominent, perhaps move it so that "Select Folder [______]" takes the whole row, and only the "Morphemizer" and "File formats" lines are reduced by it, and the button will be closer to the center and the other buttons.

I tried different layouts when I made it, but they all ended up looking worse than the current one. If you can sketch out a better layout then I'll happily look at it.

**Comment by aleksejrs** [comment]
![generators-edit](https://github.com/mortii/anki-morphs/assets/1025861/84f39af0-7f75-4c5c-aee1-72b97f9d4932)

**Comment by mortii** [comment]
this will be included in the next update
