### ISSUE TITLE
Change "Select folder" to "Select file" for Generator Output

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#256]
### Is your feature request related to a problem?

In Generators, clicking the "Generate Frequency File" or "Generate Study Plan" button opens a window called "Generator Output" that has a "Select folder" button.

The Settings window has a dropdown that assumes all frequency files are in the same folder and not subfolders.
There are only two default file names / types of output files.
So it is more useful to generate files with different file names in the same folder than files with the same names in different folder.

### Describe the solution you would like

The button should be "Select file", and open a window on the `frequency-files` folder, where you can select an existing file to overwrite or specify a new name.

**Comment by mortii** [comment]
Sure, makes a lot of sense :+1:

**Comment by mortii** [comment]
do you want the field to only display the file name or the entire path like it currently does?

**Comment by aleksejrs** [comment]
The path.
It is currently the most annoying window to me, because something like not selecting a directory makes it lose the path, and it tries to save to an read-only directory, and then the chooser opens on the home directory even though there is a path.

**Comment by mortii** [comment]
released in [v.3.1.0](https://github.com/mortii/anki-morphs/releases/tag/v3.1.0)
