### ISSUE TITLE
'Learn card now' browser action does not update seen morphs

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#27]

**Comment by Vilhelm-Ian** [comment]
Couldn't somebody just mass select and press add tag "am_known" and recalculate

**Comment by Vilhelm-Ian** [comment]
We could just make the Learn card now button just do that instead of changing it to a review and changing it's due value

**Comment by Vilhelm-Ian** [comment]
I just realized why it dosen't work anymore. IT has to do with the query I wrote. It checks "introduced:1" meanning that the card must be answered the same day. 

    #   "(introduced:1 note:ankimorphs\_sub2srs OR introduced:1 note:Basic) OR is:buried tag:am-known"
so we should bury the card and tag it as am-known

**Comment by mortii** [comment]
Sorry, I typed the wrong thing in the title, meant 'learn card now'

**Comment by mortii** [comment]
Another thing i think happens is that the 'learn card now' places the card at position 0 in the queue, which means it is not actually shown. Not sure though, I need to investigate it more in-depth first.

**Comment by mortii** [comment]
> we should bury the card and tag it as am-known

No, that would unfortunately mark all the morphs on the card as known which would make the highlighting wrong...

**Comment by mortii** [comment]
I suspect there is a really simple solution to this like just setting 'mw.reviewer.card = card' in run_learning_card_now()

**Comment by mortii** [comment]
fixed in  #29
