### ISSUE TITLE
Warning about new fields introduced with 3.0.0

### ISSUE THREAD

**Issue by fuquasteve** [mortii/anki-morphs#272]
### What is the current documentation?

[//]: # (Please add a link to the current docs page if it exists)

### What changes do you suggest?

The new fields introduce with version  3.0.0 contain a huge amount of information, much of which is of little use when reviewing cards, but which probably helps developers.  When I blindly activated them all, my collection immediately got too big to sync.

There should be a warning about activating these fields for people with large collections.

And there should some guidance about what fields actually will appear on cards and what use the other fields might be.

**Comment by mortii** [comment]
The [current docs](https://mortii.github.io/anki-morphs/user_guide/setup/settings/extra-fields.html) has this:

>> Note: The first time you select an extra field you have to do a full sync upload to AnkiWeb. If you have a lot of cards (500K+), then syncing might become a problem. Read more about it on the [Anki FAQ](https://faqs.ankiweb.net/are-there-limits-on-file-sizes-on-ankiweb.html).

>The fields contain the following:
>
>**am-all-morphs**:
>A list of the morphs.
>
>**am-all-morphs-count**:
>The number of morphs.
>
>**am-unknown-morphs**:
>A list of the morphs that are still unknown to you.
>
>**am-unknown-morphs-count**:
>The number of morphs that are still unknown to you.
>
>**am-highlighted**:
>An HTML version of the text that highlights the morphs based on learning status.
>
>**am-score:**
>The score AnkiMorphs determined the card to have
>
>**am-score-terms**:
>The individual [score](https://mortii.github.io/anki-morphs/user_guide/usage/recalc.html#scoring-algorithm) terms
>
>**am-study-morphs**:
>A list of the morphs that were unknown to you when you first studied the card.


What would you change/add to that?

**Comment by fuquasteve** [comment]
You may want to select only the fields that you actually use on your cards, for instance am-study-morphs and am-highlighted.

Perhaps this, or something with better wording, could go after "Note: The first time you select an extra field you have to do a full sync upload to AnkiWeb. If you have a lot of cards (500K+), then syncing might become a problem. "

**Comment by mortii** [comment]
how about this:

> **Important**: Extra fields add more data to your collection, so only select fields that will be useful to you.

**Comment by fuquasteve** [comment]
Sounds great.  Maybe it will make somebody like me pay closer attention to
what they are doing.  :-)

**Comment by mortii** [comment]
done :)
