### ISSUE TITLE
Cantonese frequency file - downloadable version - header not for lemma

### ISSUE THREAD

**Issue by Kirchheim** [mortii/anki-morphs#274]
### Describe the bug
Upgraded today to Ankimorphs 3.0.0 and downloaded the Cantonese frequency file.
Did not work. I think the header line is wrong.
I edited the file and now works, but the provided download needs to be corrected.

[//]: # (Please provide a clear and concise description of what the bug is.)

### Steps to reproduce the behavior

[//]: # (Example:)
[//]: # (1. Go to '...')
[//]: # (2. Click on '....')
[//]: # (3. Scroll down to '....')
[//]: # (4. See error)

### Expected behavior

[//]: # (Please provide a clear and concise description of what would expected to happen instead.)

### Screenshots

[//]: # (If applicable, add screenshots to help explain your problem, otherwise you can delete this section.)

### My AnkiMorphs settings

[//]: # (Copy and paste the json configs displayed when you go to:)
[//]: # (Tools -> Add-ons -> select "AnkiMorphs" -> click on the "Config" button on the lower right sidebar.)

### My system

[//]: # (Note: the AnkiMorphs version is found on the bottom of the AnkiMorphs settings window)

[//]: # (Example:)
[//]: # (- Operating System: Windows 11)
[//]: # (- Anki Version: 23.12.1)
[//]: # (- AnkiMorphs Version: v2.0.0)

 - Operating System:
 - Anki Version:
 - AnkiMorphs Version:

### Additional context

[//]: # (Add any additional context about the problem here, or delete this section if it's empty)

**Comment by mortii** [comment]
Oh yeah, it should be a lemma only file too. Thanks for letting me know!
