### ISSUE TITLE
PermissionError: [Errno 13]

### ISSUE THREAD

**Issue by lmoffett123** [mortii/anki-morphs#275]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "C:\Users\liamm\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 519, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "C:\Users\liamm\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 84, in <lambda>
    op=lambda _: _recalc_background_op(
  File "C:\Users\liamm\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 157, in _recalc_background_op
    _update_cards_and_notes(am_config, modify_enabled_config_filters)
  File "C:\Users\liamm\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 185, in _update_cards_and_notes
    morph_priorities: dict[tuple[str, str], int] = get_morph_priority(
  File "C:\Users\liamm\AppData\Roaming\Anki2\addons21\472573498\morph_priority_utils.py", line 63, in get_morph_priority
    return _load_morph_priorities_from_file(
  File "C:\Users\liamm\AppData\Roaming\Anki2\addons21\472573498\morph_priority_utils.py", line 80, in _load_morph_priorities_from_file
    with open(priority_file_path, mode="r+", encoding="utf-8") as csvfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\liamm\\AppData\\Roaming\\Anki2\\User 1\\priority-files\\ru-web-priority.csv'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiMorphs ['472573498', 2024-08-02T19:57, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-27T20:26, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-06-01T15:05, 'None', '']
Chinese Support 3 ['1752008591', 2024-02-25T09:37, 'None', mod]
Edit Field During Review ['1020366288', 2022-08-29T20:38, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-07-09T13:54, 'None', mod]
Hanzi Web v100 -- Form connections between your learned Hanzi and Kanji ['125468335', 2023-05-24T12:09, 'None', mod]
HyperTTS - Add speech to your flashcards ['111623432', 2024-07-16T00:33, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
ankimorphs-chinese-jieba ['1857311956', 2024-03-25T14:52, 'None', '']

===IDs of active AnkiWeb add-ons===
1020366288 111623432 125468335 1436550454 1752008591 1771074083 1857311956 31746032 472573498 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by lmoffett123** [comment]
Furthermore, it keeps prompting that the "Morph-Lemma" field is missing, and to add one in.

**Comment by lmoffett123** [comment]
Is there anyway to roll back the addon if this problem persists? AnkiMorphs is too valuable not to use for language learning.

**Comment by lmoffett123** [comment]
I do have admin access for the PC, but perhaps I wasn't doing this as the "administrator". What would you advise?

**Comment by mortii** [comment]
1. [Change the permissions](https://kb.uwec.edu/articles/drives-establishing-windows-file-and-folder-level-permissions) of the file to at least `read` for your user.
2. If that doesn't fix it, try running Anki as administrator.

**Comment by lmoffett123** [comment]
Thank you for this, now I get: 

Priority file: C:\Users\liamm\AppData\Roaming\Anki2\User 1\priority-files\ru-web-priority.csv is malformed (possibly outdated).
Priority file is missing the 'Morph-Lemma' header
Please generate a new one.

![Screenshot 2024-08-06 201054](https://github.com/user-attachments/assets/9a9f1bc0-c260-407d-a8d6-e6a3ee147e65)

The 'Morph-Lemma' is in place.

Any advice?

**Comment by lmoffett123** [comment]
![Screenshot 2024-08-06 201424](https://github.com/user-attachments/assets/227025b8-84aa-4220-b444-9676902fa729)
![Screenshot 2024-08-06 201437](https://github.com/user-attachments/assets/02cbc54e-c885-4f05-a689-411757cfe3a1)
![Screenshot 2024-08-06 201445](https://github.com/user-attachments/assets/be65ece1-7d00-4b87-a32c-5d5c57360080)

And now back to the issue we have about permissions.

**Comment by mortii** [comment]
Do you not get the permission error any more? Because I think this problem:

> Priority file is missing the 'Morph-Lemma' header

likely stems from the "permission error". Since the file cannot be read, the "Morph-Lemma" header cannot be found either.

Also, if you could provide the following, it would help me a lot:
> Copy and paste the json configs displayed when you go to:
>    (Tools -> Add-ons -> select "AnkiMorphs" -> click on the "Config" button on the lower right sidebar.)
