### ISSUE TITLE
the option "Suspend new cards with only known morphs" doesn't work with manually marked cards

### ISSUE THREAD

**Issue by buster-blue** [mortii/anki-morphs#276]
### Describe the bug

[//]: # (Please provide a clear and concise description of what the bug is.)
There's an option to suspend cards that only have known morphs on recalc, but it doesn't work if the card was marked as manually known. It only works with automatically known cards.

### Steps to reproduce the behavior

1. enable the option to suspend new cards with only known morphs
2. mark a new card with unknown morphs as known (so now all morphs are known)
3. recalc
4. the card isn't suspended

### Expected behavior

The card is suspended properly on recalc, like automatically known cards are. An alternative solution is to suspend the card immediately instead of skipping if this option is enabled.

### My AnkiMorphs settings

{
    "algorithm_all_morphs_target_difference_weight": 10,
    "algorithm_average_priority_all_morphs_weight": 0,
    "algorithm_average_priority_learning_morphs_weight": 0,
    "algorithm_learning_morphs_target_difference_weight": 10,
    "algorithm_lower_target_all_morphs": 4,
    "algorithm_lower_target_all_morphs_coefficient_a": 0.0,
    "algorithm_lower_target_all_morphs_coefficient_b": 1.0,
    "algorithm_lower_target_all_morphs_coefficient_c": 0.0,
    "algorithm_lower_target_learning_morphs": 1,
    "algorithm_lower_target_learning_morphs_coefficient_a": 6.0,
    "algorithm_lower_target_learning_morphs_coefficient_b": 0.0,
    "algorithm_lower_target_learning_morphs_coefficient_c": 0.0,
    "algorithm_total_priority_all_morphs_weight": 1,
    "algorithm_total_priority_learning_morphs_weight": 10,
    "algorithm_total_priority_unknown_morphs_weight": 10,
    "algorithm_upper_target_all_morphs": 6,
    "algorithm_upper_target_all_morphs_coefficient_a": 1.0,
    "algorithm_upper_target_all_morphs_coefficient_b": 0.0,
    "algorithm_upper_target_all_morphs_coefficient_c": 0.0,
    "algorithm_upper_target_learning_morphs": 2,
    "algorithm_upper_target_learning_morphs_coefficient_a": 6.0,
    "algorithm_upper_target_learning_morphs_coefficient_b": 0.0,
    "algorithm_upper_target_learning_morphs_coefficient_c": 0.0,
    "evaluate_morph_inflection": true,
    "evaluate_morph_lemma": false,
    "extra_difficulty": false,
    "extra_fields_display_inflections": true,
    "extra_fields_display_lemmas": false,
    "extra_highlighted": false,
    "extra_unknowns": true,
    "extra_unknowns_count": true,
    "filters": [
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": false,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": true,
            "extra_unknown_morphs": false,
            "extra_unknown_morphs_count": true,
            "field": "Expression",
            "modify": true,
            "morph_priority_selection": "priority-file.csv",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Japanese",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": false,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": true,
            "extra_unknown_morphs": false,
            "extra_unknown_morphs_count": true,
            "field": "Expression",
            "modify": true,
            "morph_priority_selection": "priority-file.csv",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Immersion Kit Japanese Sentence (my custom)",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": false,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": true,
            "extra_unknown_morphs": false,
            "extra_unknown_morphs_count": true,
            "field": "jpn",
            "modify": true,
            "morph_priority_selection": "priority-file.csv",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Tatoeba jpn",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": false,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": true,
            "extra_unknown_morphs": false,
            "extra_unknown_morphs_count": true,
            "field": "Expression",
            "modify": true,
            "morph_priority_selection": "priority-file.csv",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Japanese Core Anime Vocabulary",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        }
    ],
    "hide_inflection_toolbar": false,
    "hide_lemma_toolbar": false,
    "hide_recalc_toolbar": false,
    "interval_for_known_morphs": 5,
    "parse_ignore_bracket_contents": false,
    "parse_ignore_names_morphemizer": false,
    "parse_ignore_names_textfile": false,
    "parse_ignore_round_bracket_contents": false,
    "parse_ignore_slim_round_bracket_contents": false,
    "parse_ignore_suspended_cards_content": false,
    "preprocess_ignore_bracket_contents": false,
    "preprocess_ignore_names_morphemizer": true,
    "preprocess_ignore_names_textfile": true,
    "preprocess_ignore_round_bracket_contents": false,
    "preprocess_ignore_slim_round_bracket_contents": false,
    "preprocess_ignore_suspended_cards_content": false,
    "read_known_morphs_folder": false,
    "recalc_due_offset": 50000,
    "recalc_interval_for_known": 5,
    "recalc_move_known_new_cards_to_the_end": false,
    "recalc_number_of_morphs_to_offset": 100,
    "recalc_offset_new_cards": false,
    "recalc_on_sync": false,
    "recalc_read_known_morphs_folder": false,
    "recalc_suspend_known_new_cards": true,
    "recalc_toolbar_stats_use_known": false,
    "recalc_toolbar_stats_use_seen": true,
    "recalc_unknowns_field_shows_inflections": true,
    "recalc_unknowns_field_shows_lemmas": false,
    "shortcut_browse_all_same_unknown": "Shift+L",
    "shortcut_browse_ready_same_unknown": "L",
    "shortcut_browse_ready_same_unknown_lemma": "Ctrl+Shift+L",
    "shortcut_frequency_file_generator": "Ctrl+Shift+F",
    "shortcut_generators": "Ctrl+Shift+G",
    "shortcut_known_morphs_exporter": "Ctrl+Shift+E",
    "shortcut_learn_now": "Ctrl+Alt+N",
    "shortcut_progression": "Ctrl+Alt+P",
    "shortcut_readability_report_generator": "Ctrl+Shift+R",
    "shortcut_recalc": "Ctrl+M",
    "shortcut_set_known_and_skip": "K",
    "shortcut_settings": "Ctrl+O",
    "shortcut_view_morphemes": "Ctrl+Alt+V",
    "skip_only_known_morphs_cards": false,
    "skip_show_num_of_skipped_cards": true,
    "skip_unknown_morph_seen_today_cards": false,
    "tag_fresh": "am-fresh-morphs",
    "tag_known_automatically": "am-known-automatically",
    "tag_known_manually": "am-known-manually",
    "tag_learn_card_now": "am-learn-card-now",
    "tag_not_ready": "am-not-ready",
    "tag_ready": "am-ready",
    "toolbar_stats_use_known": false,
    "toolbar_stats_use_seen": true
}

### My system

- Operating system: Fedora Linux 39
- Anki Ver. 24.06.3
- AnkiMorphs Ver. 3.0.0

### Additional context

I suspect that the issue has something to do with checking for the presence of the "am-known-automatically" tag, which doesn't appear on manually known cards. They get "am-known-manually" instead.

I also know that ankimorphs knows that there are no unknown morphs, because the "am-unknown-morphs-count" field is "0"

**Comment by mortii** [comment]
Ah, this logic needs to be reworked:

https://github.com/mortii/anki-morphs/blob/4ccd51021b056db284b58af0140399472d007ef2/ankimorphs/tags_and_queue_utils.py#L49-L53


Thanks for reporting it!

**Comment by mortii** [comment]
should be fixed in [v3.0.1](https://github.com/mortii/anki-morphs/releases/tag/v3.0.1), thanks!
