### ISSUE TITLE
Import regex module for \p{L}

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#28]
https://github.com/kaegi/MorphMan/issues/309

The current regex fails to pick up on cases where a non letter character is between letters.

**Comment by mortii** [comment]
Could we not just add a parse option that replaces newlines with a space?

**Comment by mortii** [comment]
And for punctuation

**Comment by Vilhelm-Ian** [comment]
yes we can. That's the other route

**Comment by mortii** [comment]
Maybe it should be bundled with the existing "ignore quotation marks"-option since it basically does the same thing. We could rename it to "ignore special characters" or something.

**Comment by Vilhelm-Ian** [comment]
That's a good idea

**Comment by mortii** [comment]
Are you working on it or should I do it?

**Comment by Vilhelm-Ian** [comment]
I can give it a go. Currently working on the learn card now

**Comment by aleksejrs** [comment]
> Maybe it should be bundled with the existing "ignore quotation marks"-option since it basically does the same thing. We could rename it to "ignore special characters" or something.

Then if you disable ignoring quotation marks and your multi-line cards are parsed with words from different lines joined, that will just be wrong. Doesn't seem like an option should be needed to remove what is always wrong, especially bundles with something optional.

**Comment by Vilhelm-Ian** [comment]
> > Maybe it should be bundled with the existing "ignore quotation marks"-option since it basically does the same thing. We could rename it to "ignore special characters" or something.
> 
> Then if you disable ignoring quotation marks and your multi-line cards are parsed with words from different lines joined, that will just be wrong. Doesn't seem like an option should be needed to remove what is always wrong, especially bundled with something more optional.

morphman currently distinguishesh newline. It dosen't have issue with new lines

**Comment by Vilhelm-Ian** [comment]
only when a special character is between words

**Comment by mortii** [comment]
> Then if you disable ignoring quotation marks and your multi-line cards are parsed with words from different lines joined, that will just be wrong. Doesn't seem like an option should be needed to remove what is always wrong, especially bundled with something more optional.

> only when a special character is between words


Right, so \n doesn't have to be bundled.  but the other special characters should still be bundled? There would never be a reason to only ignore quotation marks but not the other problematic characters right?

**Comment by Vilhelm-Ian** [comment]
Correct

**Comment by mortii** [comment]
> I can give it a go. Currently working on the learn card now

Nice. Making changes to settings and config has a steep learning curve (it took me forever to make), so I can do that part if it's too bothersome. You should definitely be the one who add characters to this regex, you are more familiar with the problem than me:

https://github.com/mortii/anki-morphs/blob/7a635f27534eda800b9d88503683931a55d2fe90/ankimorphs/morph_utils.py#L39-L42

**Comment by mortii** [comment]
Once this is done I'll create a 0.3.0 release

**Comment by Vilhelm-Ian** [comment]
I will try to do it today

**Comment by Vilhelm-Ian** [comment]
Dumb question why don't we just do \w+ see the difference between the current approach:

```
 m = "hat?Das test?me fruit.loop m>h zz$oo sh»sh öhhä&öö 市市市市 βββΣΣΣΣ-ΣΣΣΣΣΣ"
re.findall(r"\w+", m)
['hat', 'Das', 'test', 'me', 'fruit', 'loop', 'm', 'h', 'zz', 'oo', 'sh', 'sh', 'öhhä', 'öö', '市市市市', 'βββΣΣΣΣ', 'ΣΣΣΣΣΣ']
```
The current  regex fails to notice special characters when they are inside a word
```
 re.findall(r"\b[^\s\d]+\b", m)
['hat?Das', 'test?me', 'fruit.loop', 'm>h', 'zz$oo', 'sh»sh', 'öhhä&öö', '市市市市', 'βββΣΣΣΣ-ΣΣΣΣΣΣ']
```

**Comment by Vilhelm-Ian** [comment]
I suggest the following regex ``\w+-\w+|\w+`` becuse sometimes you have words like 
Spider-Man
E-mail
World-wide
Up-to-date
User-friendly

If there are other edge cases we can add them later on in the same way

**Comment by mortii** [comment]
Ah, I hadn't considered making changes to only that specific morphemizer, that is a way better solution. We should probably remove the settings option then since it would be redundant and just slows the morphemizing process.

**Comment by mortii** [comment]
Apostrophes should also be included right?
``` 
\w+[-']\w+|\w+
```

**Comment by Vilhelm-Ian** [comment]
Yes things like o'clock

**Comment by Vilhelm-Ian** [comment]
Can you add this as a comment near to the regex " "god-forsaken-man"

**Comment by Vilhelm-Ian** [comment]
@mortii the current version is working perfectly. The change we made with the regex has a great effect on my collection A BUNCH(and I mean a bunch) of cards that were prior skipped are now shown to me :)

**Comment by mortii** [comment]
> @mortii Can you add this as a comment near the regex " "god-forsaken-man"

Sure, I should add some info about the '?:' part too

> @mortii the current version is working perfectly. The change we made with the regex has a great effect on my collection A BUNCH(and I mean a bunch) of cards that were prior skipped are now shown to me :)

That is amazing! You did most the work, well done! :clap:
