### ISSUE TITLE
When the interface language is Chinese, Ctrl+Z needs to be pressed twice to return to the previous card

### ISSUE THREAD

**Issue by bie-zheng** [mortii/anki-morphs#296]
### Describe the bug

[//]: # (Please provide a clear and concise description of what the bug is.)

### Steps to reproduce the behavior

1. Set language to Chinese
2. Open any deck of cards
3. Review a card
4. Press ctrl+z

### Expected behavior

- When the system language is English, press Ctrl once to return to the previous card
- Press Ctrl twice when the system language is Chinese to return to the previous card

### My system

 - Operating System:Windows 11
 - Anki Version:24.06.3
 - AnkiMorphs Version:v3.2.1

### Additional context

https://github.com/user-attachments/assets/8ef863e3-5952-4238-b26b-f46a410e3df4

[//]: # (Add any additional context about the problem here, or delete this section if it's empty)

**Comment by mortii** [comment]
Wow, that is super weird. I'll look more into it!

**Comment by mortii** [comment]
Should be fixed in [v3.2.2](https://github.com/mortii/anki-morphs/releases/tag/v3.2.2)!

Let me know if it doesn't work, and/or if you encounter any other problems :)
