### ISSUE TITLE
highlighting bug

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#38]
morphs that should have 'learning status', end up having the 'known' status sooner than they should. This is probably because other cards with that morph gets the 'am-known' tag when this morph is first leaned... Kind of a fundamental problem. Maybe introduce a 'am-learning' tag?

**Comment by Vilhelm-Ian** [comment]
I can take a  look at it

**Comment by mortii** [comment]
> I can take a look at it

If you want to, sure!

I think this is the problem:
https://github.com/mortii/anki-morphs/blob/5f4336bc883c889048caeb49261afc00734b1866/ankimorphs/recalc.py#L538-L551

We should probably differentiate between unknowns and learning.

**Comment by Vilhelm-Ian** [comment]
I am currently working on the frequency  list

**Comment by mortii** [comment]
> I am currently working on the frequency list

Ok, I can do this one. I'll finish the UI for the readability report generator first though.

**Comment by Vilhelm-Ian** [comment]
you work really fast

**Comment by mortii** [comment]
haha, nah, the bug just was more superficial than I first feared so I didn't need to change a lot.
