### ISSUE TITLE
Tags in Note Filter does not seem to work.

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#42]
![image](https://github.com/mortii/anki-morphs/assets/74698160/26004be0-c404-48f5-b9e3-32bafd3ea3cd)

My workaround is add another filter.

**Comment by HQYang1979** [comment]
On the old morphman, tags can be separated by a comma. the cards that have at least one of the tags will be filtered.

**Comment by mortii** [comment]
On AnkiMorphs it works like this:

if a note-filter has more than one tag (comma separated), then only cards that have all of those tags will be used

```
Note Type                   Tags            
1. note_type1               tag_a, tag_b
```
If you want cards that have either tag you have to do this:
```
Note Type                   Tags          
1. note_type1               tag_a  
2. note_type1               tag_b 
```

Your approach of having both tags on the same note-filter is definitely more intuative, and I'm sure everyone with a similar use-case will encounter this problem so we need to make the guide better and point this out explicitly.

It also occurs to me that note-filters can have significant overlap of cards and right now that would lead to them being recalculated  more than one time. To fix this we would have to add a new check for that, something like:

``` python
if card_id in modified_cards:
    continue
```

I'll fix those things asap. 

I personally only use one note-filter without any tags, so this was very helpful feedback, thank you so much!

**Comment by mortii** [comment]
@HQYang1979 btw, did you get names.txt to work?

**Comment by mortii** [comment]
I updated the [tags guide](https://mortii.github.io/anki-morphs/user_guide/setup/settings/note-filter.html#tags), does it make sense? Any  suggestions for making it better?

I'm terrible at writing guides, sorry!

**Comment by HQYang1979** [comment]
> @HQYang1979 btw, did you get names.txt to work?

yes, it works fine, thank you!
