### ISSUE TITLE
It takes more than 5 seconds to use the Undo command 

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#46]
When I merge two cards and find out that they are in the wrong order and try to undo, it takes more than 5 seconds to complete the command. I do have a huge note collection though, but it shouldn't take that long. And I know it is because of ankimorph, it only happens when I enable ankimorph.

![image](https://github.com/mortii/anki-morphs/assets/74698160/ee11bfd5-32c7-4b3a-86c3-150945dff4df)

**Comment by mortii** [comment]
Interesting, I didn't even know you could merge cards.

When you review/study cards and you undo does that also take a long time?

**Comment by HQYang1979** [comment]
the addon is AJT merge note.

yes it takes a long time when I review/study cards and I undo.

**Comment by mortii** [comment]
That is definitely not ideal.... Undoing is a nightmare because the add-on loses track of which morphs have been seen today, and it's not a trivial thing to fix. Maybe it could be run on a background thread though, that would prevent the freezing at least. I'll see what I can do.

**Comment by mortii** [comment]
[v0.6.1-alpha changelog](https://github.com/mortii/anki-morphs/releases/tag/v0.6.1-alpha):
> When undoing (Ctrl+Z) the 'seen morphs' list is rebuilt from scratch to make sure it is up to date. That can cause Anki to freeze depending on how many cards you have reviewed today and how good your hardware is. The freezing is now fixed by running it on a background thread and showing a progress window.
