### ISSUE TITLE
Ability to prioritize frequency over i+1 cards

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#53]
**Is your feature request related to a problem? Please describe.**
Using the custom frequency option. I have a lot of cards that are within the realm of the custom frequency but they are not i+1 I want to see them

**Describe the solution you'd like**
An option to prioritize a card difficult over number of unknown morphs

**Additional context**
MorphMan used to have this feature.

mortii I can add it myself. Just asking if you would be okay

**Comment by Vilhelm-Ian** [comment]
I fixed the frequency list issue that was not prioritizing morphs in the frequency list. I don't need this anymore. I am just going to leave it open so you see it and hear your thought. 

I think this feature would be against what AnkiMorphs is trying to achieve

**Comment by mortii** [comment]
> An option to prioritize a card difficult over number of unknown morphs

I'm not really sure what you mean by that. Could you give an example?

**Comment by Vilhelm-Ian** [comment]
Let's say I don't know the words. "The" "Cat" but both of them are really common.
So the option if it would be enabled I would get the card "The hungry cat" instead of a card where I know all but one word.

After I fixed frequency.csv option.  I don't need this option anymore. And think it's the opposite of what AnkiMorphs should do. But maybe some user would want to prioritize frequency over comprehensibility. But I think we should just advice users like that to just import more anki cards

**Comment by mortii** [comment]
I think that would just be a problem of having poor morph priorities. Like you say, with a custom frequency file this would go away. Definitely something to be aware of, and we should add it to the FAQ if someone else also experiences something like this. 

Thank you!
