### ISSUE TITLE
Suggest to users to create custom frequency list for shows once they reach 4k words

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#68]
## What is the current documentation?

It dosen't mention the benefit of custom frequency lists. It only says that they can make a custom frequency list.

## What changes do you suggest?
https://youtu.be/ey2nsLTH1jM?t=87 you should watch a 1 or 2 from the timestap where it is. Basically someone did a calculation that after 4k words a general frequency list has diminishing returns for specific media. And to solve that problem one should generate a custom frequency list for the show. Here is an example I am currently reading the hunger games. The words mine, bow, arrow, bakery, district are not common words in general but in the book they are really common. And me knowing those words grately benefits my reading.

It dosen't have to mention the 4k mark it can just mention the benefits

**Comment by mortii** [comment]
Interesting! That would be a great addition to the [tips & tricks](https://mortii.github.io/anki-morphs/user_guide/setup/tips-and-tricks.html) section. I'll gladly accept a PR on this.

**Comment by mortii** [comment]
@Vilhelm-Ian should I write something about this real quick, or do you want to do it?

**Comment by Vilhelm-Ian** [comment]
I am not good with English 😳

**Comment by Vilhelm-Ian** [comment]
Great. I loved the overfitting part
