### ISSUE TITLE
Error pressing L

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#69]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.23590
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-24 21:13:07
Add-ons possibly involved: ⁨ankimorphs-alpha⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\472573498\reviewing_utils.py", line 237, in <lambda>
    lambda: browse_same_morphs(
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\472573498\browser_utils.py", line 58, in browse_same_morphs
    card_ids = am_db.get_ids_of_cards_with_same_morphs(card_id, search_unknowns)
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\472573498\ankimorphs_db.py", line 247, in get_ids_of_cards_with_same_morphs
    raw_card_ids = self.con.execute(
sqlite3.OperationalError: near "am": syntax error

**Comment by mortii** [comment]
Very interesting. I suspect you have a morph that accidentally produces sql syntax. We should sanitize the morph inputs for the query.

I'm not able to reproduce the problems with my cards. Is it possible for you to upload your cards somewhere for me to download?

**Comment by HQYang1979** [comment]
> Very interesting. I suspect you have a morph that accidentally produces sql syntax. We should sanitize the morph inputs for the query.
> 
> I'm not able to reproduce the problems with my cards. Is it possible for you to upload your cards somewhere for me to download? 

the error message disappeared. Let me upload my collection here.

**Comment by mortii** [comment]
> the error message disappeared. 

if my assumption is correct then it depends on which card you used 'L' on.

If you go to `Browse -> Today -> Studied` you can then right click on cards -> Browse same morphs, and you might find which card produced the error. 

This might be impractical if you studied a lot of cards today however....

**Comment by HQYang1979** [comment]
I cannot reproduce the error, so... maybe just consider it closed.

**Comment by mortii** [comment]
Ok, let me know if it happens again!
