### ISSUE TITLE
Are you removing redability analyzer

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#7]
https://github.com/mortii/anki-morphs/commit/8ba3f39e854bb252dc84331951c404ff21d0fa15

I find readability analyzer to be really useful feature. It helps me do deep dives. And help me choose which media to consume. 

here is what a deep dive is https://www.youtube.com/watch?v=ey2nsLTH1jM&

**Comment by mortii** [comment]
Only temporarily, I will rebuild it from scratch after I'm done with the core features.
