### ISSUE TITLE
Incompatible with Edit Field During Review Cloze when "mark as name" press

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#74]
![image](https://github.com/mortii/anki-morphs/assets/74698160/067d147d-2af9-47b8-8ef0-2d3da8083ae0)

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/2e05c027-d15a-4ca0-ad67-8c90df9c11dc)
And the same name keeps popping up, it cannot be skipped. I thought it was supposed to skip it in the whole collection.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 
![image](https://github.com/mortii/anki-morphs/assets/81630959/5f88cf0a-5ad4-451e-9bd4-604c59d9d7ef)
Do you have this enabled

**Comment by Vilhelm-Ian** [comment]
Also what is the issue with edit field during cloze. You can't edit the field or the name is not saved to the names.txt file?

**Comment by HQYang1979** [comment]
> Also what is the issue with edit field during cloze. You can't edit the field or the name is not saved to the names.txt file?

Edit field during cloze is an addon that let you edit the fields while review. I am not trying to edit the name, it is just the working of the said addon.
https://ankiweb.net/shared/info/385888438

**Comment by HQYang1979** [comment]
It is just this message.
![image](https://github.com/mortii/anki-morphs/assets/74698160/69b7cb08-5fe7-4fed-bd7f-c426b496374c)
I understand what happened now.

I disabled Edit field during cloze, and it works fine now.

The reason of the error message is that, EFDC does not have time to do the assesment of saving on the fly and ankimorph's prompt message "xxx card buried" interrupts it.

I'll close this one then if you guys have no obejction.

**Comment by HQYang1979** [comment]
> @HQYang1979 before you close it does the name still keep popping up for you

No more.

**Comment by Vilhelm-Ian** [comment]
you can close the issue
