### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#75]
1) Multi-language support, which should also reflect on frequency.txt. I agree 50K as a threshold in order to maintain recalc efficiency.

2) "mark as name" should recalc the whole collection and make those cards with only the name being unknown buried.
![image](https://github.com/mortii/anki-morphs/assets/74698160/c81696b3-21fb-47fb-89b6-20d6f1ed91e5)
![image](https://github.com/mortii/anki-morphs/assets/74698160/2504c6f4-830d-405c-bd84-d4e9bdeab7c5)

3) delete one card should not bury related cards.
I see that when I delete one card (because of bad audio or bad sentence), it shows skipping multiple cards. I am not sure what cards are skipped, but I assume they are related cards. I think only K can skip related cards.

Please keep this thread alive, I'll add something along I use the addon.

**Comment by HQYang1979** [comment]
With 0.7 coming, I feel the vibe of using the addon now.

**Comment by Vilhelm-Ian** [comment]
can you change this part of your title "(Please keep me alive) " it's offputing to me

**Comment by HQYang1979** [comment]
> can you change this part of your title "(Please keep me alive) " it's offputing to me

sorry....

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 I am going to take a look at your issues.

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/ffe04e2c-1ccc-4903-a1e0-7366de522d0c)
I like this part a lot! Much smoother than morphman!

**Comment by HQYang1979** [comment]
> @HQYang1979 can you elaborate on your first part. To have multi lang support you need to create to different frequency lists. One for the first language and another for the second. And use those frequency lists for their desired note types

My understanding is that the addon can only recognize one frequency.txt, there is no JPfrequency.txt or Enfrequency.txt, am I right? I then have to pack all the words from different languages into the same frequency.txt.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 you have to put a frequency list with .csv file extension in your profile folder under a folder that has frequency in it. And if you don't have a frequency .csv file youcan generate one using the generate frequency list sub menu in Tools->AnkiMorphs

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/7db372a5-327e-45cf-8b4d-2df1e4cc30bf)

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 did you manage to get the frequency lists to work?

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/54ca87ab-6e3a-403f-b306-55ae39c65b92)


> @HQYang1979 did you manage to get the frequency lists to work?

Yes, thank you so much. It's the karma of not reading the manual....

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 I just tried the mark as name functionallity it works as expected it buries all the cards where the name is the only known morph. It's just that the dialog that says "Buried 1 cards" is wrong.

Can you close this issue

mortii if you happen to read this I am pleasently suprised that other people also use the feature "mark as name"

**Comment by HQYang1979** [comment]
mark as name is a great feature, of course we'll use it.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 can you close this issue. I believe that both issues are solved
