### ISSUE TITLE
The K (skip) Rational

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#78]
![image](https://github.com/mortii/anki-morphs/assets/74698160/37ce7440-5f74-4e0b-b177-b0a48956317e)

Morphman logic: when press K, all related cards are buried, and they are re-arranged to the end of the whole collection's queue. Next day they are unburied, but will appear only when you finish the whole deck.

Ankimorph logic: when press K, all related cards are suspended, and they will never appear unless unsuspended.

I'd say morphman is a bit winning, because when at the end of the day, you will still want to see those cards. A second chance maybe.

But it is just my thought.

You guys are doing an excellent job, I feel like I can delete morphman now.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 that's not true. AnkiMorphs by default buries those cards. It only suspends them if 
![image](https://github.com/mortii/anki-morphs/assets/81630959/7699fe40-af42-45e9-ae8f-c488c65a8998)
you have that option enabled

**Comment by HQYang1979** [comment]
I got this error message when I recalc, is it because my frequency list is too long? Three langs 50K.

**Comment by HQYang1979** [comment]
> @HQYang1979 that's not true. AnkiMorphs by default buries those cards. It only suspends them if ![image](https://private-user-images.githubusercontent.com/81630959/286968230-7699fe40-af42-45e9-ae8f-c488c65a8998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTkzNDEsIm5iZiI6MTcwMTM1OTA0MSwicGF0aCI6Ii84MTYzMDk1OS8yODY5NjgyMzAtNzY5OWZlNDAtYWY0Mi00NWU5LWFlOGYtYzQ4OGM2NWE4OTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE1NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDEwZWRlNDc5OTBhZDhiODRjOTE4ZDJkOThiNzA0ODkyNjA5MzI0NWU0OTIwOGM4NjgzYzY0YjgxMTg3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BQZZ-7v75Mqiq8k89yQwGvbIc8hbg0J5Q9ZAoboa5mI) you have that option enabled

I see.  Thank you very much!

**Comment by HQYang1979** [comment]
mmm, I unchecked Suspend new cards with only known morphs, and I could not see the action of skipping xxx cards now....

**Comment by mortii** [comment]
> Morphman logic: when press K, all related cards are buried, and they are re-arranged to the end of the whole collection's queue. Next day they are unburied, but will appear only when you finish the whole deck.

@HQYang1979 The default AnkiMorphs does the same thing, but it does not immediately bury all related cards--related cards are only buried if the user "sees" them, i.e. they are skipped.

Do you think the related cards should be buried immediately? I will be slower, so I'm not sure if it is a good idea.

**Comment by HQYang1979** [comment]
Come to think of it, "Suspend cards with only known morphs" (SCWOKM) might be a good thing.

When I review on morphman in a small deck (like just one episode or one series), it will bury the related cards (with the same unknown/known word, or siblings), and move them to the end of the queue; the next day, the buried siblings will be unburied but you are not going to see them soon because they are at the end of the queue. I continue reviewing until all T1 cards are done. At this time the siblings will appear.

I cannot say this is the best way to do, but that's the way I was with morphman. But if you review a huge deck (1M cards etc.), you will not see the end of the queue that soon).

I am getting used to SCWOKM, I think it might work. I can always unsuspend them. At the moment, I just think that moving the siblings to the end of the queue might be a better option.

**Comment by mortii** [comment]
> When I review on morphman in a small deck (like just one episode or one series), it will bury the related cards (with the same unknown/known word, or siblings), and move them to the end of the queue; the next day, the buried siblings will be unburied but you are not going to see them soon because they are at the end of the queue. I continue reviewing until all T1 cards are done. At this time the siblings will appear.

Ah I see, that is a very different approach to using the add-on compared to how I'm doing it, but it might be a great approach. 

Are you using Recalc at any point in this process? If you don't use Recalc in AnkiMorphs then the cards will not be moved to the back of the queue.

**Comment by HQYang1979** [comment]
> Ah I see, that is a very different approach to using the add-on compared to how I'm doing it, but it might be a great approach.

It gives you the illusion of satisfaction that wow I finish a DECK!

**Comment by HQYang1979** [comment]
> Do you get a different result than when you do them on morphman? If you don't get the same result, what is different? Does the 4th step not work?

I think this is exactly morphman's been doing. If we follow these steps, the result should be the same.

**Comment by HQYang1979** [comment]
when the cards or notes are skipped, where will they go if not suspended? Are they going to the end of the collection queue? @mortii @Vilhelm-Ian

**Comment by Vilhelm-Ian** [comment]
> when the cards or notes are skipped, where will they go if not suspended? Are they going to the end of the collection queue? @mortii @Vilhelm-Ian

Currently there are two things that happen.

1. By defauflt when they are recalculated they go to the end of the que
2. When you *learn* a card every card with the same unknown morphs is *buried* for the current *day*
3. If you press mark as name same happens as two

**Comment by mortii** [comment]
> I think this is exactly morphman's been doing. If we follow these steps, the result should be the same.
> 
> Having said that, I kinda like this feature, can it be a option here: you can choose to use suspend or bury instead of just suspend or bury. And it sure will give users more ways to explore their own approaches of study.
> 
> ![image](https://private-user-images.githubusercontent.com/74698160/287331113-0cb46f11-9948-424f-b25b-996d1cb5665d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzI2NjMsIm5iZiI6MTcwMTUzMjM2MywicGF0aCI6Ii83NDY5ODE2MC8yODczMzExMTMtMGNiNDZmMTEtOTk0OC00MjRmLWIyNWItOTk2ZDFjYjU2NjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE1NTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDcwNjFiZDNiYzZlNTFjMDM3MTY0ZTZlODQ2ODFlZmM0ZWEzMDc2MzhlMzE1YzgzNTdiMWRjYjQxNzk4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDFGkO_PjE0UHrPuewXmEIszRG_g4033A_aZXKmusu0)

@HQYang1979 If the steps works as described then the option you describe ("Bury new cards with only known morphs"), should not be neccessary right? It would basically do what is already done by default

**Comment by HQYang1979** [comment]
> @HQYang1979 If the steps work then the option you describe ("Bury new cards with only known morphs"), should not be neccessary right? It would basically do what is already done by default

Yes, @Vilhelm-Ian yesterday explained it to me, it is not necessary. I've been using Ankimorph whole day long, it's smooth and as expected. 

Thank you guys for the effort! I have no need for morphman now.
