### ISSUE TITLE
skipping xxx cards not showing

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#80]
mmm, I unchecked Suspend new cards with only known morphs, and I could not see the action of skipping xxx cards now....

_Originally posted by @HQYang1979 in https://github.com/mortii/anki-morphs/issues/78#issuecomment-1834053413_

**Comment by mortii** [comment]
I might have mixed them up when the settings are saved, I'll check.

**Comment by HQYang1979** [comment]
> I might have mixed them up when the settings are saved, I'll check.

I see them back on when I review from the uppermost deck.

**Comment by Vilhelm-Ian** [comment]
@mortii I tested the newest version today. The settings are correct. Most likely hq accidently checked the setting

**Comment by mortii** [comment]
Is this the thing you are missing @HQYang1979 ?
![image](https://github.com/mortii/anki-morphs/assets/15674619/6c530ad0-6c41-44c5-8392-d2c184b50ed0)

**Comment by HQYang1979** [comment]
it came back all right. Thank you!
