### ISSUE TITLE
Multiple Field Analysis Support

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#82]
I know we've discussed this, but still I am writing to ask to support multiple field analysis.

I've got Vocabulary card and Sentence card (Subs2srs), a vocab and a sentence will not be on the same field, but they need to be sorted.

**Comment by mortii** [comment]
Does the Vocabulary cards and Sentence cards have the same note type?

**Comment by HQYang1979** [comment]
> Do the Vocabulary cards and Sentence cards have the same note type?

Yes, same note type. 

This is my vocab card:
![image](https://github.com/mortii/anki-morphs/assets/74698160/2ddeb9bf-c96f-44b9-9b44-cbc0d49df3d5)
This is my sentence card:
![image](https://github.com/mortii/anki-morphs/assets/74698160/6070c676-6d25-4934-9715-82f0dc8b7e22)
And then I will merge both of them using AJT Merge Note:
![image](https://github.com/mortii/anki-morphs/assets/74698160/deb3a90c-8785-4fd7-a00e-feec9a22c098)
To be:
![image](https://github.com/mortii/anki-morphs/assets/74698160/7c367271-d05b-41ca-b62a-f8c4f7ed988b)

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 how would you want the cards to be sorted. If you have vocab cards and the same vocab in the sentence card. Then the addon would only show you vocab cards since they are shorter.

**Comment by HQYang1979** [comment]
> @HQYang1979 how would you want the cards to be sorted. If you have vocab cards and the same vocab in the sentence card. Then the addon would only show you vocab cards since they are shorter.

That is fine, it is how morphman did it. I can always press L if I need to find another card of the same morph.

But I wonder how you would do the highlight....

**Comment by HQYang1979** [comment]
> @HQYang1979 I personally don't use highlighting the useful part of the highlighting is telling which one is the unknown morph. What I do is I add on the back side I add {{Unknown_Morphs}}. Maybe that will help you.>

This is great idea, I never thought about it! One thing bugging me is Ankimorph generate lots of html code in the field makes my 1M card collection hugely bulky.
And I don't know how to get rid of them, maybe have to use find and replace.

> Also what about the part where yoou won't ever see cards with sentences unless you press L. You can do the same thing with having different note types. >

And I don't know L can also list other card types with the same morph. I make only one card type for one language. I'll try this one though.

Thank you, great advices!

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 to get rid of the HTML use this in your find and replace <[^>]*>

**Comment by HQYang1979** [comment]
> @HQYang1979 to get rid of the HTML use this in your find and replace <[^>]*>
Be sure to select the correct note type

Thank you so much. I am lousy at regex

**Comment by mortii** [comment]
> This is great idea, I never thought about it! One thing bugging me is Ankimorph generate lots of html code in the field makes my 1M card collection hugely bulky. And I don't know how to get rid of them, maybe have to use find and replace. ![image](https://private-user-images.githubusercontent.com/74698160/287295218-6fae0fea-e34c-4f72-b131-ea48131c541b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDc3MzEsIm5iZiI6MTcwMTQ0NzQzMSwicGF0aCI6Ii83NDY5ODE2MC8yODcyOTUyMTgtNmZhZTBmZWEtZTM0Yy00ZjcyLWIxMzEtZWE0ODEzMWM1NDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZGZkYjQwMWEyZmY4ODY4NTU0NGQwZWQxMjljYTRlY2YyYzVmZjJlMDlkMDU2MzViYjZiNThmZGJkODAzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0q42eNZQKntw9xSeWJMbFfDh9ZZ1erTIo2A9kxTHyk)

I have a bad feeling that you are might be using it wrong....

Are you using a separate field on your card, specifically made to hold the highlighted text? Like this:

![Screenshot from 2023-12-01 17-25-45](https://github.com/mortii/anki-morphs/assets/15674619/632964c8-3d6a-4251-9017-9e4df28b777e)

The `highlighted-version` field simply keeps the duplicate version of my `Japanese` field, so there should never be any reason to search through the `highlighted-version` field, just search through the `Japanese` field instead.

**Comment by HQYang1979** [comment]
> The highlighted-version field simply keeps the duplicate version of my Japanese field, so there should never be any reason to search through the highlighted-version field, just search through the Japanese field instead.

I do have separate Japanese and Highlighted version fields. I have no idea why the Japanese field got the html code and I cannot reproduce it, neither do I want to though.

**Comment by mortii** [comment]
@HQYang1979 supporting multiple fields is just not practical at all, so it won't be implemented, sorry. Hopefully you can find a workaround.
