### ISSUE TITLE
exclude cards with specific tags

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#83]
is it possible to exclude cards with specific tags...I mean the other way around

_Originally posted by @HQYang1979 in https://github.com/mortii/anki-morphs/issues/81#issuecomment-1835424780_

**Comment by mortii** [comment]
I have not thought about that before. Give me a couple of hours and I'll try to figure out of it is feasible or not.

**Comment by Vilhelm-Ian** [comment]
@mortii it's a simple fix just do this in the query -tag:am-known adding a - before query negates it

**Comment by Vilhelm-Ian** [comment]
I think we should be vary on how many settings we add to the addon. The biggest complaint people had with th original was that it was too difficult to use

**Comment by HQYang1979** [comment]
This reason I proposed this is because I have these cards:

![image](https://github.com/mortii/anki-morphs/assets/74698160/3c5930eb-1b49-48f2-be78-2ca0a9c69bc8)

I would like to exclude these cards by tags.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979  can't you manually bury them or suspend them

**Comment by HQYang1979** [comment]
<@HQYang1979 A problem with what you want is that in anki what tag one card has every card for the note type will have it. So if you plan on excluding a certain type of card from your note type it won't work>

No, I can always add a new tag to the cards I want to exclude. This is what I did with Morphman, only that I did it to include instead of exclude.

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 if you add a tag to a card you are also adding the tag to the NOTE

**Comment by HQYang1979** [comment]
> @HQYang1979 can't you manually bury them or suspend them. And if you need to review them put them in a different deck

This deck is actually very good material I downloaded from ankiweb, but it is in a messy format. What I do is try to modify it one by one.
I've already put them in a different deck, but without excluding them, they will be analyzed. 

So I am thinking if I can exclude them by tags....

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 can't you delete or suspend those based on their tags.

**Comment by HQYang1979** [comment]
> Do you want to add tags to cards not in a note filter so they will be treted like they are in the note filter?

I see what you mean. Sorry for causing confusion. I use card and note pretty meaning the same thing.

**Comment by HQYang1979** [comment]
> @HQYang1979 can't you delete or suspend those based on their tags.

I suppose I can suspend them. Well, I might just find another work around.

**Comment by mortii** [comment]
@Vilhelm-Ian @HQYang1979 @aleksejrs 

![Screenshot from 2023-12-06 21-00-19](https://github.com/mortii/anki-morphs/assets/15674619/6e752908-dd24-4ff9-9e90-692f731c9b32)

Thoughts on this? Is it too confusing?

**Comment by aleksejrs** [comment]
If the UI doesn't even know about hierarchical tags, it will be unusable.

**Comment by mortii** [comment]
Added searchbar that supports regex
![Screenshot from 2023-12-07 12-34-02](https://github.com/mortii/anki-morphs/assets/15674619/f79b7c4e-1237-491f-b019-c7c067dcc5fe)

**Comment by mortii** [comment]
> If the UI doesn't even know about hierarchical tags, it will be unusable. 

@aleksejrs I have no idea how hierarchical tags could be displayed in this kind of view.... collapsible rows would be weird I think... Is having a searchbar good enough?

**Comment by mortii** [comment]
> > make sure someone can't select to include and exclude the same time. I think radio buttons would make more sense
> 
> @Vilhelm-Ian yep, if one checkbox is selected the other one is automatically unselected. If we used radio buttons there would have to be three of them (exclude, include, none), so I think checkboxes is probably better.

I changed my mind, having radio buttons  would make it more explicit that there are three options not just two... I'll try to implement that instead.

**Comment by mortii** [comment]
![Screenshot from 2023-12-07 16-12-14](https://github.com/mortii/anki-morphs/assets/15674619/59c93ac4-6869-46c5-a1d8-6b76127fd066)

Suggestions for better column names? I don't love "None".

**Comment by mortii** [comment]
Let's continue in a discussion instead: #90
