### ISSUE TITLE
Korean support

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#85]
Korean texts has spacing between words like English but not quite. It is an inflectional language, the particles stick together with nouns to tell the roles of the nouns are playing, and it has the same kind of word conjugation as Japanese.

It is that I cannot use Language with spaces, is there something like Mecab for Korean?

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 what you want is on the project road map. Just so you know it's probably the hardest thing to add. So be patient with this one :)

**Comment by mortii** [comment]
> @HQYang1979 what you want is on the project road map. Just so you know it's probably the hardest thing to add. So be patient with this one :)

Yep,  #62 will add Korean.
