### ISSUE TITLE
Tip users on how to restore card queue if they want to revert Ankimorphs changes.

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#87]
Do you think it is necessary to let users go back to the way the decks are before they use Ankimorph?

I did when I just started to use the previous version of Ankimorph.

Ankimorph modifies only the new cards queue. So sort all the new cards in the browser by the order of created, select them all and right click and select reposition, then back to the default.

May the force be with you.

**Comment by mortii** [comment]
> Ankimorph modifies only the new cards queue. So sort all the new cards in the browser by the order of created, select them all and right click and select reposition, then back to the default.

Good tip! I will add it to the [tips & tricks section.](https://mortii.github.io/anki-morphs/user_guide/setup/tips-and-tricks.html)

**Comment by mortii** [comment]
Added [Reverting AnkiMorphs changes section](https://mortii.github.io/anki-morphs/user_guide/setup/tips-and-tricks.html#reverting-ankimorphs-changes) to tips and tricks.

Thanks for the suggestion!

**Comment by aleksejrs** [comment]
> Added [Reverting AnkiMorphs changes section](https://mortii.github.io/anki-morphs/user_guide/setup/tips-and-tricks.html#reverting-ankimorphs-changes) to tips and tricks.

Is that section blank?
