### ISSUE TITLE
Anki Freeze During Review with Ankimorph

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#88]
Anki freezes sometimes during review with Ankimorph, I have to Ctrl+Alt+Shift to kill it. Sadly there is no error messages but I pretty sure it has something to do with Ankimorph, mostly happens when skipping the cards.

**Comment by HQYang1979** [comment]
I'll have to wait for next freeze....

**Comment by mortii** [comment]
Let's give this a 3 week period, if it hasn't happened after that then the issue will be closed automatically.

**Comment by HQYang1979** [comment]
I haven't encountered any freeze until now, though I've been heavily using the addon.

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/a0e954f1-0c58-4409-8672-0e860dd9200b)

Freeze....

**Comment by HQYang1979** [comment]
> @HQYang1979 What happens if you click the 'x' button on the little pop-up window?

Nothing happens. It doesn't respond.

**Comment by mortii** [comment]
I think this is probably a bug in the Anki API. I also think it might be a race condition bug, which is worst case scenario. I can't think of any way to solve this, unfortunately....

We should add this to the known bugs section. Hopefully it keeps being a rare occurrence.

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/5219a54e-e427-4b99-8f0a-7cdab8661d57)
Freezed

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/be9db8d1-aa65-4f1c-833b-0b90632915cc)
Freezed

**Comment by Vilhelm-Ian** [comment]
@HQYang1979  have you noticed any common behaviour. Can you run anki from now on through the terminal everytime

**Comment by HQYang1979** [comment]
> @HQYang1979  have you noticed any common behaviour. Can you run anki from now on through the terminal everytime

I will run through terminal from now on

**Comment by mortii** [comment]
> ![image](https://private-user-images.githubusercontent.com/74698160/292694578-be9db8d1-aa65-4f1c-833b-0b90632915cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDMxNjYsIm5iZiI6MTcwMzUwMjg2NiwicGF0aCI6Ii83NDY5ODE2MC8yOTI2OTQ1NzgtYmU5ZGI4ZDEtYWE2NS00ZjFjLTgzM2ItMGI5MDYzMjkxNWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDExMTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNjdmYWViODhiZWQzN2E3ZGE5MjIwYWU3Y2NkMzgwMjdjZjA0M2YxZjIxYmUyZDRhODYyMTAwNDlkMGRjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O4r7j11Eld2mJ8uw-9BFMT4wljcNAhRdtE14QZ7_sCM) Freezed

Interesting... It could also potentially be other add-ons interfering. Maybe we can add more logging to make debugging easier.

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/26ebf88d-c54c-4e62-ae31-21b061680310)
Freezed when press undone on browser (undo the merge)

**Comment by mortii** [comment]
@HQYang1979 perfect, its another add-on that is causing the problem. What's the name of the 3858888438 add-on?

**Comment by HQYang1979** [comment]
> @HQYang1979 perfect, its another add-on that is causing the problem. What's the name of the 3858888438 add-on?

Edit-Field-During-Review-Cloze

**Comment by mortii** [comment]
> Edit-Field-During-Review-Cloze

 Okay, I'll add it to the known problems section :+1:

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/c4be427e-a9db-4be9-b38b-669c3a1638f9)

I am not sure if this freezed is related to the ankimorph.

**Comment by mortii** [comment]
> ![image](https://private-user-images.githubusercontent.com/74698160/293160170-c4be427e-a9db-4be9-b38b-669c3a1638f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjM4NjQsIm5iZiI6MTcwMzc2MzU2NCwicGF0aCI6Ii83NDY5ODE2MC8yOTMxNjAxNzAtYzRiZTQyN2UtYTlkYi00YmU5LWIzOGItNjY5YzNhMTYzOGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDExMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OTEwYWFhODA2MmExZjAyMTY3NTJiNjY2ODkyOWI4MDE0YmViYWNkOGY3ZGNmY2YyMmQwYTRjOGY1NTdmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-Tro2y7w5vo2MRSH4bmvb47nREJHxhNfHgQwy9BxHY)
> 
> I am not sure if this freezed is related to the ankimorph.

Not that I can tell from the terminal at least. Maybe exiting the reviewer and browser before creating a backup might help--less likely for add-ons to interrupt anki.

**Comment by HQYang1979** [comment]
> > ![image](https://private-user-images.githubusercontent.com/74698160/293160170-c4be427e-a9db-4be9-b38b-669c3a1638f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjM4NjQsIm5iZiI6MTcwMzc2MzU2NCwicGF0aCI6Ii83NDY5ODE2MC8yOTMxNjAxNzAtYzRiZTQyN2UtYTlkYi00YmU5LWIzOGItNjY5YzNhMTYzOGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDExMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OTEwYWFhODA2MmExZjAyMTY3NTJiNjY2ODkyOWI4MDE0YmViYWNkOGY3ZGNmY2YyMmQwYTRjOGY1NTdmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-Tro2y7w5vo2MRSH4bmvb47nREJHxhNfHgQwy9BxHY)
> > 
> > I am not sure if this freezed is related to the ankimorph.
> 
> Not that I can tell from the terminal at least. Maybe exiting the reviewer and browser before creating a backup might help--less likely for add-ons to interrupt anki.

It actually is an auto backup by Anki itself

**Comment by mortii** [comment]
> It actually is an auto backup by Anki itself

Interesting, didn't know that existed.

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/67237965-e106-4fd4-a9a2-0a00f85ebc93)
another freeze during normal review

**Comment by mortii** [comment]
> ![image](https://private-user-images.githubusercontent.com/74698160/293369975-67237965-e106-4fd4-a9a2-0a00f85ebc93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTU4ODIsIm5iZiI6MTcwMzg1NTU4MiwicGF0aCI6Ii83NDY5ODE2MC8yOTMzNjk5NzUtNjcyMzc5NjUtZTEwNi00ZmQ0LWE5YTItMGEwMGY4NWViYzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEzMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMGQyNWM2MTFhOWM3MmRkZTQ3NzBjZmE5NDU1NzVhYWM1ZGNiM2RlMWY3ZmI2NDc3ZDE1YjMwMzY3OGE2NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SfQBqrGwfmu74ZltyEb4qIkUI2wXkCkqsJJ2HCARl-o) another freeze during normal review

That sucks. Since there are no errors shown, and it happens before the AnkiMorphs starts looping through cards, I again think its a rare bug in the Anki API. Since AM uses this background operation API call every time a card is answered this potentially rare bug could become more noticeable then in other add-ons.

It could still potentially be another add-on that is somehow interfering. If you disable all the other add-ons and you still get the problem then it would narrow it down to a bug in either ankimorphs or the anki api.

**Comment by mortii** [comment]
Updated known problems: https://mortii.github.io/anki-morphs/user_guide/known-problems.html#freezing-when-reviewing

Sorry I couldn't fix it :(
