### ISSUE TITLE
Use MorphMan-style UI for Extra Fields, because the dropdown-based one is dangerous and gives no benefits

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#95]
https://github.com/mortii/anki-morphs/issues/47#issuecomment-1828465811

In MorphMan, each auto-filled field had the same name in every note type.
* You have to add the fields you want to the note types you want them in
* Pros:
    * The field will be filled automatically if you added it.
    * If the field is called "MorphMan_Unknowns", you will never use it for important data.
    * You don't have to wonder what the field name is, if it's the same everywhere.
* Cons:
    * You can't have different extra field names for different types. I don't know what the use of that could be, since you wouldn't want to share those fields with other people anyway.

![289586373-9ad4a1cd-83c6-48da-a8e1-7e2680da1b01](https://github.com/mortii/anki-morphs/assets/1025861/dcceee02-9ff5-44a8-a6ce-09de36bc18ff)

At the screenshot of anki-morphs, each note type can have its own names for auto-filled fields, and you have to select the right fields for each note type where you want them.
* You have to add the fields you want to the note types you want them in, and select them.
* Pros: I don't know.
   * You can appropriate an existing field of a note type as an extra field?
   * Or use a field somebody else used for anki-morphs but named differently?
   * Or use a formerly MorphMan field?
* Cons:
    * You have to select the fields for each note type. I have tens of note types, and maybe ten of them have new cards.
    * Is dropdown (number of extra fields × number of processed note types) is an opportunity to choose the wrong field, e.g. by pressing End or Down when the wrong element is focused.

**Comment by mortii** [comment]
> [#47 (comment)](https://github.com/mortii/anki-morphs/issues/47#issuecomment-1828465811)
> 
> In MorphMan, each auto-filled field had the same name in every note type.
> * Pros:
>   * The field will be filled automatically if you added it.

Whaaaat? I always made them manually. I haven't thought about the fact that you can add fields to notes programatically... if the extra fields are always static then you would never encounter the problem of over-writing fields by accident. 

That is a million times better than the current approach, thanks for pointing it out!

**Comment by mortii** [comment]
I've made a discussion thread for this: #99
